# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_shape_5c165d6dd7
ROOST_METHOD_SIG_HASH=add_shape_af74209d91


Scenario 1: Successful addition of a new shape
Details:
  TestName: test_add_shape_successful
  Description: This test is intended to verify if a new shape with label, bounding box and difficulty can be added correctly.
Execution:
  Arrange: Initialize an object instance and prepare the bounding box data.
  Act: Invoke the add_shape function, passing the label, prepared bounding box and difficulty of the shape.
  Assert: Check if the newly added shape is present in the shapes list with correct properties.
Validation:
  This test validates that the function can successfully handle proper data inputs and add a new shape to the list. The correct addition of shape information is crucial for the functionality of the imaging class.

Scenario 2: Addition of a shape with invalid bounding box values
Details:
  TestName: test_add_shape_invalid_values
  Description: This test is intended to verify the behavior of the function when trying to add a shape with invalid bounding box values.
Execution:
  Arrange: Initialize an object instance and prepare invalid bounding box data.
  Act: Invoke the add_shape function, passing the label, prepared bounding box, and difficulty of the shape.
  Assert: Verify if an appropriate exception is raised.
Validation:
  It's crucial that the function handles the input data properly and confirms if the bounding box data is within the acceptable range. This scenario will help to check if invalid data inputs are properly handled by the function.

Scenario 3: Adding shape with duplicate label
Details:
  TestName: test_add_shape_duplicate_label
  Description: This test aims to check the behavior of the function when a shape with an already existing label is added.
Execution:
  Arrange: Initialize an object instance, add a shape with a specific label.
  Act: Call the add_shape function again with the same label, prepared bounding box and difficulty.
  Assert: Check if this new shape was added to the shapes list.
Validation:
  According to the given function code, the same shape label can exist multiple times in the shapes list. Hence, it's important to validate if the function handles the addition of shapes with duplicate labels correctly. Configuration errors and unexpected functionality can be avoided with this validation.

Please note that these scenarios are based on an assumption of certain behaviors as the complete code context is not provided. These scenarios may need to be updated based on the intended functionality of the method.
"""

# ********RoostGPT********
import pytest
import sys

from xml.etree import ElementTree
from xml.etree.ElementTree import Element, SubElement
from lxml import etree
import codecs
from libs.constants import DEFAULT_ENCODING
from libs.ustr import ustr

from pascal_voc_io import PascalVocReader

class Test_PascalVocReaderAddShape:
      
    def test_add_shape_successful(self):
        file_path = "<file_path>" # TODO: user provides file path
        reader = PascalVocReader(file_path)
        label = 'rectangle'
        elem = ElementTree.Element("bndbox")
        SubElement(elem, "xmin").text = '5'
        SubElement(elem, "ymin").text = '5'
        SubElement(elem, "xmax").text = '15'
        SubElement(elem, "ymax").text = '15'
        reader.add_shape(label, elem, False)
        assert reader.shapes[-1][0] == label

    def test_add_shape_invalid_values(self):
        file_path = "<file_path>" # TODO: user provides file path
        reader = PascalVocReader(file_path)
        label = 'rectangle'
        elem = ElementTree.Element("bndbox")
        SubElement(elem, "xmin").text = '-5'
        SubElement(elem, "ymin").text = '-5'
        SubElement(elem, "xmax").text = '15'
        SubElement(elem, "ymax").text = '15'
        with pytest.raises(ValueError) as exc_info:
            reader.add_shape(label, elem, False)
        assert 'value must be > 0' in str(exc_info.value)

    def test_add_shape_duplicate_label(self):
        file_path = "<file_path>" # TODO: user provides file path
        reader = PascalVocReader(file_path)
        label = 'rectangle'
        elem = ElementTree.Element("bndbox")
        SubElement(elem, "xmin").text = '5'
        SubElement(elem, "ymin").text = '5'
        SubElement(elem, "xmax").text = '15'
        SubElement(elem, "ymax").text = '15'
        reader.add_shape(label, elem, False)
        reader.add_shape(label, elem, False)
        assert len(reader.shapes) == 2
