# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=pop_point_179cdfaaa0
ROOST_METHOD_SIG_HASH=pop_point_785af4543b


Scenario 1: Pop from Non-empty List of Points
Details:
  TestName: test_pop_from_non_empty_points_list
  Description: This test is intended to verify that the function 'pop_point' properly removes and returns the last point in the list, if the list of points is not empty.
Execution:
  Arrange: Initialize a non-empty list of points, setup 'points' attribute of the class to this non-empty list.
  Act: Invoke the 'pop_point' function.
  Assert: Check that the returned point matches the last point that was in the list and that the last point has been removed from the 'points' list.
Validation:
  Inside the function definition, the key operation condition is that the list of points is not empty. In this scenario, we are checking this very condition by providing a non-empty 'points' list. This is crucial for ensuring the function behaves as intended when dealing with non-empty list.

Scenario 2: Pop from Empty List of Points
Details:
  TestName: test_pop_from_empty_points_list
  Description: This test is meant to verify that the function 'pop_point' returns None when the points array is empty.
Execution:
  Arrange: Initialize an empty list of points and set the 'points' attribute of the class to this empty list.
  Act: Invoke the 'pop_point' function.
  Assert: Verify that the function returns None, indicating that no point could be popped as the list is empty.
Validation:
  As the function is designed to return None if the list is empty, this scenario validates that condition by providing an empty 'points' list. This is critical for verifying the function's appropriately handled corner cases involving empty inputs.
  
Scenario 3: Verify List is Shortened After Pop
Details:
  TestName: test_list_size_after_pop
  Description: This test is meant to verify that the function 'pop_point' correctly shortens the points list size after popping.
Execution:
  Arrange: Initialize a non-empty list of points, setup 'points' attribute of the class to this non-empty list.
  Act: Invoke the 'pop_point' function.
  Assert: Check that the length of the 'points' list has been reduced by one after popping.
Validation:
  This scenario is essential to confirm that the function not only returns the last point but also removes it from the list of points. This is inline with the standard behavior of the 'pop' function in Python programming.
"""

# ********RoostGPT********
# pytest unit tests for the pop_point method of Shape

import pytest
try:
    from shape import Shape
except ImportError:
    print("Unable to import Shape class. Make sure the file and class exists.")
    sys.exit(1)

class Test_ShapePopPoint:

    def setup(self):
        self.test_point = QPointF(5,6)

    # Scenario 1: Pop from Non-empty List of Points
    @pytest.mark.regression
    def test_pop_from_non_empty_points_list(self):
        shape = Shape()
        shape.points.append(self.test_point)  # Arrange

        popped_point = shape.pop_point()  # Act

        # Assert
        assert popped_point == self.test_point
        assert self.test_point not in shape.points 

    # Scenario 2: Pop from Empty List of Points
    @pytest.mark.regression
    def test_pop_from_empty_points_list(self):
        shape = Shape()  # Arrange with an empty list of points by default      

        popped_point = shape.pop_point()  # Act

        # Assert
        assert popped_point is None

    # Scenario 3: Verify List is Shortened After Pop 
    @pytest.mark.regression
    def test_list_size_after_pop(self):
        shape = Shape()
        shape.points.append(self.test_point)  # Arrange
        initial_length = len(shape.points)

        shape.pop_point()  # Act

        # Assert
        assert len(shape.points) == initial_length - 1
