# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=un_highlight_670896a5fd
ROOST_METHOD_SIG_HASH=un_highlight_2cf450567e


Scenario 1: Verify highlighting is removed when the highlighted shape is un_highlighted
Details:
  TestName: test_un_highlight_clears_highlighting_when_shape_is_highlighted
  Description: This test verifies that when a highlighted shape is passed to the un_highlight method, the method removes the highlighting on the shape by calling the highlight_clear() method of the shape. It also sets the h_shape and h_vertex attributes of the canvas to None.
Execution:
  Arrange: Create an instance of the Canvas class. Create a shape and set it to be the h_shape of the canvas with some highlighting.
  Act: Call the un_highlight method with the highlighted shape as parameter.
  Assert: Check that the highlight of the shape has been cleared and the h_shape and h_vertex attributes of the canvas are set to None.
Validation:
  This test is important to verify that the un_highlight method performs its function as expected, and maintains the integrity of the canvas by removing highlighting where it is not supposed to be.

Scenario 2: Verify no change in highlights when an unhighlighted shape is un_highlighted.
Details:
  TestName: test_un_highlight_does_nothing_on_unhighlighted_shape
  Description: This test is to verify that unhighlight does not affect a shape that is not highlighted. Any current highlights should not be affected.
Execution:
  Arrange: Create an instance of the Canvas class with some highlighted shape. Also have another shape that is not highlighted.
  Act: Call the un_highlight method with the unhighlighted shape as the parameter.
  Assert: All highlighted shapes before the function call are still highlighted after the call. No shapes were unhighlighted.
Validation:
  The integrity of the highlighting is an essential feature of the Canvas class. This test ensures highlights are only removed when necessary and should stay consistent otherwise.

Scenario 3: Test un_highlight on None parameter
Details:
  TestName: test_un_highlight_on_None_parameter
  Description: The un_highlight method also supports None as an input parameter. This test verifies that it unhighlights h_shape if the parameter is None.
Execution:
  Arrange: Create an instance of the canvas class with a highlighted shape.
  Act: Call the un_highlight method with None as the parameter.
  Assert: h_shape is unhighlighted and h_shape and h_vertex values are None.
Validation:
  This test is important as it ensures the un_highlight method is fully functional and behaves as expected when called in an unparameterized form. This has implications for maintaining the consistency and accuracy of the canvas.

Scenario 4: Verify un_highlight behavior when 'shape' passed does not match self.h_shape
Details:
  TestName: test_un_highlight_no_action_when_different_shape_passed
  Description: This test ensures that if a different shape (other than the currently highlighted one) is passed into the function, the method will take no action.
Execution:
  Arrange: Create an instance of the Canvas class with some highlighted shape. Also create a different shape.
  Act: Call the un_highlight method with the different shape as the parameter.
  Assert: The originally highlighted shape remains highlighted. No modifications were made.
Validation:
  This test is important to ensure that the un_highlight method only operates on the specified shape. This prevents unnecessary or unintended modification and maintains the model's integrity.

"""

# ********RoostGPT********
import pytest
from libs.shape import Shape
from PyQt5.QtGui import *

# additional import for defining Canvas
from canvas import Canvas


class Test_CanvasUnHighlight:

    @pytest.mark.regression
    def test_un_highlight_clears_highlighting_when_shape_is_highlighted(self):
        # Arrange
        canvas = Canvas()
        highlighted_shape = Shape()
        highlighted_shape.highlight = True
        canvas.h_shape = highlighted_shape
        canvas.h_vertex = QPoint(10,10)

        # Act
        canvas.un_highlight(highlighted_shape)

        # Assert
        assert not highlighted_shape.highlight
        assert canvas.h_shape is None
        assert canvas.h_vertex is None

    @pytest.mark.regression
    def test_un_highlight_does_nothing_on_unhighlighted_shape(self):
        # Arrange
        canvas = Canvas()
        highlighted_shape = Shape()
        highlighted_shape.highlight = True
        canvas.h_shape = highlighted_shape
        unhighlighted_shape = Shape()
        unhighlighted_shape.highlight = False

        # Act
        canvas.un_highlight(unhighlighted_shape)

        # Assert
        assert highlighted_shape.highlight
        assert canvas.h_shape is highlighted_shape
        assert canvas.h_vertex is not None

    @pytest.mark.regression
    def test_un_highlight_on_None_parameter(self):
        # Arrange
        canvas = Canvas()
        highlighted_shape = Shape()
        highlighted_shape.highlight = True
        canvas.h_shape = highlighted_shape
        canvas.h_vertex = QPoint(10,10)

        # Act
        canvas.un_highlight(None)

        # Assert
        assert not highlighted_shape.highlight
        assert canvas.h_shape is None
        assert canvas.h_vertex is None

    @pytest.mark.regression
    def test_un_highlight_no_action_when_different_shape_passed(self):
        # Arrange
        canvas = Canvas()
        highlighted_shape = Shape()
        highlighted_shape.highlight = True
        canvas.h_shape = highlighted_shape
        different_shape = Shape()

        # Act
        canvas.un_highlight(different_shape)

        # Assert
        assert highlighted_shape.highlight
        assert canvas.h_shape is highlighted_shape
        assert canvas.h_vertex is not None
