# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=__init___55bfcabe40
ROOST_METHOD_SIG_HASH=__init___648def6d80


Scenario 1: Testing the constructor with the correct and usual parameters
Details:
TestName: test_init_default
Description: This test verifies the correct execution and initialization of the class attributes when the constructor is called with correct and usual parameters.
Execution:
  Arrange: The setup involves the creation of the variables that will be passed as parameters to the function.
  Act: The function is invoked by creating a new object, passing the necessary parameters to it.
  Assert: The test will check if the attributes of the created object match the passed parameters.
Validation:
  The importance of this test lies in validating the primary and expected behavior of the function. The execution of the constructor with standard parameters must work without exceptions, maintaining the consistency and integrity of the object.

Scenario 2: Verifying the default behavior of the constructor when optional parameters are not passed
Details:
TestName: test_init_with_missing_optional_parameters
Description: This test verifies the function's behavior when the optional parameters (`database_src` and `local_img_path`) are not provided by the user, expecting the function to use default values.
Execution:
  Arrange: The setup involves the creation of the remaining variables that will be passed as parameters to the function, omitting the optional ones.
  Act: The function is invoked by creating a new object, passing only the required parameters to it.
  Assert: The test will check if the function used the default values for the omitted parameters and if the object attributes match the expected values.
Validation:
  This test is essential to ensure the function can handle cases when some arguments are absent yet still function correctly and consistently using its default parameters.

Scenario 3: Checking the reaction of the function to unusual values for the parameters
Details:
TestName: test_init_with_unusual_parameters
Description: This test wants to evaluate the function's resilience and flexibility when faced with unusual, yet valid, values for its parameters.
Execution:
  Arrange: The setup consists of preparing the variables to be passed to the function, which will have values outside of their regular boundaries but still within their valid ranges.
  Act: The function is invoked by creating a new object with these unusual parameters.
  Assert: The test will check if the function correctly handles these unusual parameters, if it exceptions are raised or strange behaviors lose the consistency of the created object.
Validation:
  The importance of this test is to ensure that even when the function receives unusual parameters, it can still handle them correctly, preserving the integrity of the system and its robustness.

Scenario 4: Verifying automatic constructor behavior for additional functionalities
Details:
TestName: test_init_addition_behavior
Description: This test is meant to verify that automatic functionalities, such as automatic population of `self.box_list` or auto verification under certain conditions, carried out in the constructor work as intended.
Execution:
  Arrange: Initialize necessary variables and objects.
  Act: The function is invoked with parameters that cause additional behavior in the constructor.
  Assert: The test will check if the additional functionalities work as expected and modify the object as intended.
Validation:
  This is crucial to ensure that any additional behavior within the constructor works in harmony with the basic initialization, ensuring the created object's correctness and functionality.
"""

# ********RoostGPT********
import pytest
import json
from pathlib import Path
from libs.constants import DEFAULT_ENCODING
from create_ml_io import CreateMLWriter

class Test_CreateMlWriterInit:

    @pytest.mark.positive
    def test_init_default(self):
        # Arrange
        folder_name = 'folder_test'
        filename = 'filename_test'
        img_size = [500, 500]
        shapes = [{'shape_type': 'rectangle', 'points': [[1, 1],[2, 2]]}]
        output_file = 'output'
        database_src ='data_src'
        local_img_path = 'local_path'
        
        # Act
        obj = CreateMLWriter(folder_name, filename, img_size, shapes, output_file, database_src, local_img_path)
        
        # Assert
        assert obj.folder_name == folder_name
        assert obj.filename == filename
        assert obj.database_src == database_src
        assert obj.img_size == img_size
        assert obj.shapes == shapes
        assert obj.output_file == output_file
        assert obj.local_img_path == local_img_path
        assert obj.verified == False
        assert obj.box_list == []

    @pytest.mark.positive
    def test_init_with_missing_optional_parameters(self):
        # Arrange
        folder_name = 'folder_test'
        filename = 'filename_test'
        img_size = [500, 500]
        shapes = [{'shape_type': 'rectangle', 'points': [[1, 1],[2, 2]]}]
        output_file = 'output'
        
        # Act
        obj = CreateMLWriter(folder_name, filename, img_size, shapes, output_file)
        
        # Assert
        assert obj.folder_name == folder_name
        assert obj.filename == filename
        assert obj.database_src == 'Unknown'
        assert obj.img_size == img_size
        assert obj.shapes == shapes
        assert obj.output_file == output_file
        assert obj.local_img_path == None
        assert obj.verified == False
        assert obj.box_list == []

    @pytest.mark.negative
    def test_init_with_unusual_parameters(self):
        # Arrange
        folder_name = 123
        filename = 456
        img_size = "size"
        shapes = "shape"
        output_file = 789
        database_src = True
        local_img_path = 10.11
        
        # Act
        obj = CreateMLWriter(folder_name, filename, img_size, shapes, output_file, database_src, local_img_path)
        
        # Assert
        assert obj.folder_name == folder_name
        assert obj.filename == filename
        assert obj.database_src == database_src
        assert obj.img_size == img_size
        assert obj.shapes == shapes
        assert obj.output_file == output_file
        assert obj.local_img_path == local_img_path
        assert obj.verified == False
        assert obj.box_list == []

    @pytest.mark.smoke
    def test_init_addition_behavior(self):
        # Arrange
        folder_name = 'folder_test'
        filename = 'filename_test'
        img_size = [500, 500]
        shapes = [{'shape_type': 'rectangle', 'points': [[1, 1],[2, 2]]}]
        output_file = 'output'
        database_src ='data_src'
        local_img_path = 'local_path'
        
        # Act with parameters that can trigger additional behaviour: keeping database_src as Unknown
        obj = CreateMLWriter(folder_name, filename, img_size, shapes, output_file, 'Unknown', local_img_path)
        
        # Assert; here we are checking the default behaviour of the constructor
        assert obj.folder_name == folder_name
        assert obj.filename == filename
        assert obj.database_src == 'Unknown'
        assert obj.img_size == img_size
        assert obj.shapes == shapes
        assert obj.output_file == output_file
        assert obj.local_img_path == local_img_path
        assert obj.verified == False
        assert obj.box_list == []
