# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_point_758b128a07
ROOST_METHOD_SIG_HASH=add_point_658e056db9


```
Scenario 1: Test to Add Point when Max Points Haven't Been Reached
Details:
  TestName: test_add_point_when_max_not_reached
  Description: This test ensures that when the "reach_max_points" method returns false, implying that maximum points haven't been reached, a new point can be added to the points list.
Execution:
  Arrange: Create an instance of the class, ensuring that the "reach_max_points" method will return false.
  Act: Invoke the add_point method, passing in a valid point as parameter.
  Assert: The points list attribute of the class instance should include the newly added point. 
Validation:
  This test asserts the functionality of the add_point method in its most basic expected operation - adding a new point to the points list when the max points have not been reached. 

Scenario 2: Test not to Add Point When Max Points Have Been Reached
Details:
  TestName: test_not_add_point_when_max_reached
  Description: This test verifies that when the "reach_max_points" method returns true, indicating that maximum points have been reached, no new points can be added to the points list.
Execution:
  Arrange: Create an instance of the class and fill the points list up to the maximum capacity. Ensure that the "reach_max_points" method will return true.
  Act: Invoke the add_point method, passing in a valid point as a parameter.
  Assert: The points list attribute of the class instance should not include the new point - in other words, the length of the list should remain the same.
Validation:
  This test ensures that the application adheres to the limitation of a maximum amount of points, validating the applicability of this limit within the add_point function. 

Scenario 3: Test to Add Point with Various Unique Points
Details:
  TestName: test_add_unique_points
  Description: This test serves to confirm that different unique points can be added successfully to the points list.
Execution:
  Arrange: Create an instance of the class ensuring the "reach_max_points" method will return false for the number of points to be added. 
  Act: Invoke the add_point method multiple times, each with a unique point as a parameter.
  Assert: The points list attribute of the class instance should include all the unique points that were added.
Validation:
  This test verifies the application functionality when dealing with unique values, making sure unique points are successfully added to the points list, rather than ignored or incorrectly handled.
```

"""

# ********RoostGPT********
import pytest
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from shape import Shape

class Test_ShapeAddPoint:
    @pytest.mark.valid
    def test_add_point_when_max_not_reached(self):
        # Arrange
        shape1 = Shape()
        shape1.reach_max_points = lambda: False
        test_point = QPointF(10, 20)

        # Act
        shape1.add_point(test_point)

        # Assert
        assert test_point in shape1.points

    @pytest.mark.invalid
    def test_not_add_point_when_max_reached(self):
        # Arrange
        shape2 = Shape()
        shape2.reach_max_points = lambda: True
        test_point = QPointF(30, 40)

        # Fill the points up to the maximum capacity
        shape2.points = [QPointF(i, i) for i in range(4)]
        
        len_before_add = len(shape2.points)

        # Act
        shape2.add_point(test_point)

        # Assert
        assert len(shape2.points) == len_before_add

    @pytest.mark.valid
    def test_add_unique_points(self):
        # Arrange
        shape3 = Shape()
        shape3.reach_max_points = lambda: False

        # Act
        for i in range(10):
            shape3.add_point(QPointF(i, i))

        # Assert
        for i in range(10):
            assert QPointF(i, i) in shape3.points
