# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=get_shapes_b7f01a2e37
ROOST_METHOD_SIG_HASH=get_shapes_bc815932c4


Scenario 1: Get shapes from the initial list
Details:
  TestName: test_initialize_get_shapes
  Description: This test focuses on demonstrating that the get_shapes function will return the initial shape list as defined for the object under normal conditions.
Execution:
  Arrange: Initialize an object with a certain shape list.
  Act: Invoke the get_shapes function with this object.
  Assert: Confirm that the function returns the initial shape list unaltered.
Validation:
  This test ensures that get_shapes correctly retrieves the initial shape list as defined in the object, showcasing the function's basic storage and retrieval functionality.

Scenario 2: Get shapes from an empty list
Details:
  TestName: test_empty_get_shapes
  Description: This test is designed to verify that the get_shapes correctly handles situations when there are no shapes in the list.
Execution:
  Arrange: Initialize an object with an empty shape list.
  Act: Invoke the get_shapes function with this object.
  Assert: Confirm that the function returns an empty list.
Validation:
  Important in determining if the function can gracefully handle edge cases where no shapes are present. It's a marker of robustness and will aid in preventing unwanted errors in these situations.

Scenario 3: Check state preservation between calls
Details:
  TestName: test_state_preservation_get_shapes
  Description: This test checks whether the function preserves the state of the object between calls, ensuring that the same result is returned.
Execution:
  Arrange: Initialize an object with a non-empty shape list.
  Act: Call the get_shapes function twice on this object.
  Assert: Check that the same list is returned in both cases.
Validation:
  This is essential in maintaining program consistency. The tests should confirm that multiple calls to the function don't alter the initial state of the object and always return the same result.

Scenario 4: Get shapes from a list with varying data types
Details:
  TestName: test_varying_datatypes_get_shapes
  Description: This test verifies that the get_shapes function correctly handles shape lists with varying data types, returning the list as it is.
Execution:
  Arrange: Initialize an object with a shape list containing various data types.
  Act: Invoke the get_shapes function on this object.
  Assert: Confirm the function returns the shape list unaltered.
Validation:
  This test verifies data versatility. It's important since the ability to handle varying data types is essential for the function's overall flexibility and usefulness.
"""

# ********RoostGPT********
import sys
from xml.etree import ElementTree
from xml.etree.ElementTree import Element, SubElement
from lxml import etree
import codecs
from libs.constants import DEFAULT_ENCODING
from libs.ustr import ustr
from pascal_voc_io import PascalVocReader
import pytest


class Test_PascalVocReaderGetShapes:
    
    # Scenario 1: Get shapes from the initial list
    def test_initialize_get_shapes(self):
        reader = PascalVocReader('folder', 'filename', (100, 100))
        reader.shapes = [(1, 2, 3, 4, 5), (1, 3, 5, 7, 9), (2, 4, 6, 8, 10)]
        assert reader.get_shapes() == [(1, 2, 3, 4, 5), (1, 3, 5, 7, 9), (2, 4, 6, 8, 10)]
        
    # Scenario 2: Get shapes from an empty list
    def test_empty_get_shapes(self):
        reader = PascalVocReader('folder', 'filename', (100, 100))
        assert reader.get_shapes() == []
        
    # Scenario 3: Check state preservation between calls
    def test_state_preservation_get_shapes(self):
        reader = PascalVocReader('folder', 'filename', (100, 100))
        reader.shapes = [(1, 2, 3, 4, 5), (1, 3, 5, 7, 9), (2, 4, 6, 8, 10)]
        assert reader.get_shapes() == [(1, 2, 3, 4, 5), (1, 3, 5, 7, 9), (2, 4, 6, 8, 10)]
        assert reader.get_shapes() == [(1, 2, 3, 4, 5), (1, 3, 5, 7, 9), (2, 4, 6, 8, 10)]
        
    # Scenario 4: Get shapes from a list with varying data types
    def test_varying_datatypes_get_shapes(self):
        reader = PascalVocReader('folder', 'filename', (100, 100))
        reader.shapes = [(1, 'a', 3.0, [4, 5], (6, 7)), ('a', 'b', 'c', 'd', 'e'), (1, 2, 3, 4, 5)]
        assert reader.get_shapes() == [(1, 'a', 3.0, [4, 5], (6, 7)), ('a', 'b', 'c', 'd', 'e'), (1, 2, 3, 4, 5)]
