# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=focusOutEvent_ab8d634468
ROOST_METHOD_SIG_HASH=focusOutEvent_ab45164106


Scenario 1: Validate the function response when focusOutEvent is triggered.
Details:
   TestName: test_focusOutEvent
   Description: This test is designed to ensure that the method "focusOutEvent" correctly triggers the method "restore_cursor" when the widget loses focus. This feature is crucial for maintaining accurate cursor behavior in the application.
   
Execution:
   Arrange: An instance of the Canvas class has to be initiated, and focus should be given to the widget.
   Act: The focus should be moved away from the Canvas widget to trigger the focusOutEvent.
   Assert: The expected outcome should be the restoration of the overridden cursor. This will be verified by checking if the "restore_cursor" function is called.
   
Validation:
   This scenario validates that when the Canvas widget loses focus, the cursor is restored to its original state by invoking the "restore_cursor" method. Maintaining accurate cursor states is critical for interacting with the GUI, ensuring the usability of the application.  

Scenario 2: Validate the function behavior when a focusOutEvent occurs, and there is no previous cursor state.
Details:
   TestName: test_focusOutEvent_noPreviousCursorState
   Description: This test aims to verify the method's behavior when a focusOutEvent occurs, but there's no previous cursor state to restore.

Execution:
   Arrange: An instance of the Canvas class should be initiated without any overridden cursor state.
   Act: Trigger the focusOutEvent by moving the focus away from the Canvas widget.
   Assert: The expected outcome should be the method "restore_cursor" attempting to restore the cursor state even if no previous cursor state is available.
   
Validation:
   This scenario checks the robustness of the method, ensuring it doesn't crash or throw errors when there's no previous cursor state to restore. Thus, maintains the program's stability during user interactions under all circumstances. 

Scenario 3: Validate the function behavior when multiple rapid focusOutEvents are triggered.
Details:
   TestName: test_multiple_rapid_focusOutEvents
   Description: This test is to verify the method's behavior when multiple rapid focus out events are triggered, imitating erratic mouse movements.

Execution:
   Arrange: An instance of the Canvas class should be initiated with focus.
   Act: Multiple fast focus shifts away from the Canvas widget should be triggered.
   Assert: The expected outcome should be each focusOutEvent invoking the "restore_cursor" method successfully.
   
Validation:
   This scenario validates that the function can handle a sequence of rapid focus shifts without skipping the invocation of the "restore_cursor" method or affecting the final cursor state. This ensures that the application user interface behaves accurately, even under rapid or erratic interactions.

"""

# ********RoostGPT********
import unittest
from unittest.mock import Mock, call
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
import sys
# Since modules cannot be imported directly if they are sibling folders (Refer point 3 in instructions)
sys.path.insert(0, '../libs/')   

from canvas import Canvas

class Test_CanvasFocusOutEvent(unittest.TestCase):

    def setUp(self):
        self.app = QApplication([])
        self.canvas = Canvas()
        self.canvas.restore_cursor = Mock()
    
    #Fix in Function Name: using camelCase and all are small letters with no spaces
    def testFocusOutEvent(self):
        self.canvas.setFocus()
        self.canvas.focusOutEvent(QFocusEvent(QEvent.FocusOut))
        self.canvas.restore_cursor.assert_called_once()

    #Same fix done here Function name modified: Proper Naming Convention Followed
    def testFocusOutEventNoPreviousCursorState(self):
        self.canvas.override_cursor = None
        self.canvas.focusOutEvent(QFocusEvent(QEvent.FocusOut))
        self.canvas.restore_cursor.assert_not_called()

    #Same fix done here Function name modified: Proper Naming Convention Followed
    #"assert_called()" function not found in unittest package, assumes developer meant to use "assert_called_once()"
    def testMultipleRapidFocusOutEvents(self):
        self.canvas.setFocus()
        for _ in range(5):
            self.canvas.focusOutEvent(QFocusEvent(QEvent.FocusOut))
        calls = [call()] * 5
        self.canvas.restore_cursor.assert_has_calls(calls)
    
    def tearDown(self):
        # Clean up after the test
        del self.canvas

if __name__ == '__main__':
    unittest.main()
