# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=paint_8f29f5d294
ROOST_METHOD_SIG_HASH=paint_25a70dd4b3


Scenario 1: Check Object Initialization and Default Parameters
Details:
  TestName: test_paint_object_initialization
  Description: This test is intended to verify if the objects are properly initialized and default parameters are set as expected when we create a new paint instance
Execution:
  Arrange: Create an object for the class with some parameters, like label and difficult attributes.
  Act: Initialize the object.
  Assert: Check if expected default parameters and provided parameters are set as attributes of the object.
Validation:
  This test ensures the proper initialization of object attributes, and it confirms that there are no unintended alterations during object initialization, which is fundamental for the subsequent function behavior.

Scenario 2: Verification of Line and Vertex Path Creation
Details:
  TestName: test_path_creation
  Description: The test focuses on the creation of line and vertex paths when the paint function is invoked.
Execution:
  Arrange: Initialize a paint object and add points to it.
  Act: Call the paint function on the object with a simulated QPainter object.
  Assert: Verify that the QPainterPath of line and vertex paths are created and points exist in the path.
Validation:
  Paths' creation is a key feature of the paint function. This test verifies that paths are correctly created with the provided points in a consecutive manner.

Scenario 3: Closing of the Line Path
Details:
  TestName: test_line_path_closure
  Description: This test checks if the line path closes when the function is_closed returns True.
Execution:
  Arrange: Create a paint object and add points to it. Make sure the is_closed() method returns True.
  Act: Call the paint method on the object with a simulated QPainter object.
  Assert: Check if the first and the last point in the line path are the same, implying the path has closed.
Validation:
  This test is important as it validates the correctness of the function to close the line path when needed.

Scenario 4: Label Painting
Details:
  TestName: test_label_painting
  Description: This test is made to make sure that the label of the paint function is correctly depicted on the canvas when the attribute paint_label is set to True.
Execution:
  Arrange: Initialize a paint object, toggle paint_label to True, and set a label.
  Act: Invoke the paint method using a simulated QPainter object.
  Assert: Validate that the QPainter's drawText method is called with appropriate coordinates and label.
Validation:
  Label drawing functionality is a key part of the paint function. Using this test, we ensure that labels are correctly depicted and drawn at the right location.

Scenario 5: Fill Path
Details:
  TestName: test_path_fill
  Description: The test verifies if the path is filled with the correct color when the fill attribute is True in the paint object.
Execution:
  Arrange: Initialize a paint object with few points and the fill attribute set as True.
  Act: Run the paint function with a simulated QPainter object.
  Assert: Check if fillPath function is invoked with the correct color for the line path.
Validation:
  This test is important because it validates whether the correct color fill is applied to the line path when the fill attribute is set to True, thereby verifying the color selection logic in the paint function.
"""

# ********RoostGPT********
import sys
import pytest
from PyQt5.QtGui import QPainter, QPainterPath, QPen, QColor, QFont
from PyQt5.QtCore import QPointF, QPoint
from shape import Shape


class Test_ShapePaint:

    @pytest.fixture
    def qpainter(self):
        return QPainter()

    @pytest.fixture
    def shape(self):
        shape = Shape("TestShape", QColor(0, 255, 0, 128), False, True)
        shape.addPoint(QPointF(0, 0))
        shape.addPoint(QPointF(1, 1))
        shape.close()
        return shape

    def test_paint_object_initialization(self, shape):
        assert shape.label == "TestShape"
        assert shape.line_color == QColor(0, 255, 0, 128)
        assert not shape.difficult
        assert shape.paint_label

    def test_path_creation(self, qpainter, shape):
        shape.paint(qpainter)
        assert qpainter.path().elementCount() == 1
        assert qpainter.path().contains(QPointF(0, 0))
        assert qpainter.path().contains(QPointF(1, 1))

    def test_line_path_closure(self, qpainter, shape):
        shape.paint(qpainter)
        path = qpainter.path()
        assert path.elementAt(0).x == path.elementAt(path.elementCount() - 1).x
        assert path.elementAt(0).y == path.elementAt(path.elementCount() - 1).y

    def test_label_painting(self, qpainter, shape):
        font = QFont()
        font.setPointSize(shape.label_font_size)
        font.setBold(True)

        qpainter.setFont(font)
        qpainter.drawText(0, int(1.25 * shape.label_font_size), shape.label)
        shape.paint(qpainter)

        text_items = [i for i in qpainter.items() if isinstance(i, QGraphicsTextItem)]
        assert len(text_items) == 1
        assert text_items[0].toPlainText() == shape.label

    def test_path_fill(self, qpainter, shape):
        shape.fill = True
        shape.paint(qpainter)

        painter_path = qpainter.path()
        assert qpainter.brush() == QColor(255, 0, 0, 128)
        assert painter_path.contains(QPointF(0, 0))
        assert painter_path.contains(QPointF(1, 1))
