# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=finalise_14d046a442
ROOST_METHOD_SIG_HASH=finalise_6b3c8dab4e


Scenario 1: Validate the finalising operation when the first point of the current shape is the same as the last
Details:
  TestName: test_finalise_operation_with_same_initial_and_final_point
  Description: This test validates whether the finalise function is able to handle cases where the first and the last points of a shape are the same.
Execution:
  Arrange: Create a Canvas instance and initialize the 'current' attribute with a Shape object having the first and last points the same.
  Act: Invoke the 'finalise' method on the Canvas instance.
  Assert: Validate that 'current' attribute is set to None
Validation:
  The function should be able to finalize and clear the current shape when the first and the last points are the same. The expected result aligns with the business requirement of maintaining integrity of shapes on the canvas.

Scenario 2: Validate the finalising operation when the first point of the current shape is different from the last
Details:
  TestName: test_finalise_operation_with_different_initial_and_final_point
  Description: This test validates whether the finalise function closes the current shape correctly and adds it to the shapes list when the first and the last point are different.
Execution:
  Arrange: Create a Canvas instance and initialize the 'current' attribute with a Shape object having the first and last points different.
  Act: Invoke the 'finalise' method on the Canvas instance.
  Assert: Ensure that the 'current' attribute is set to None and the Shape object is added to the shapes list.
Validation:
  The function should be able to finalize the current shape by closing it and adding it to the Canvas's shape list. This aligns with the business requirement of maintaining a record of completed shapes on the canvas.

Scenario 3: Validate the hiding state after finalising operation
Details:
  TestName: test_finalise_operation_hiding_state
  Description: This test validates whether the finalise function resets the hiding state to False after finalizing current shape.
Execution:
  Arrange: Create a Canvas instance and set the '_hide_background' attribute to True.
  Act: Invoke the 'finalise' method on the Canvas instance.
  Assert: Validate that '_hide_background' attribute is set to False
Validation:
  The function should ensure the visibility of the background after finalizing a shape, which is essential for a user-friendly canvas drawing experience.

Scenario 4: Validate the emission of new shape signal after finalising operation
Details:
  TestName: test_finalise_operation_new_shape_signal
  Description: This test verifies whether a new shape signal is emitted after the current shape is finalized.
Execution:
  Arrange: Create a Canvas instance and hook a qt signal spy to 'newShape' signal.
  Act: Invoke the 'finalise' method on the Canvas instance.
  Assert: Validate that 'newShape' signal is emitted.
Validation:
  Emitting the 'newShape' signal after a shape is finalized is vital in notifying other components of the application about the creation of a new shape. This ensures that the UI stays updated and captures all business logic interactions.
"""

# ********RoostGPT********
import pytest
from unittest.mock import MagicMock
from PyQt5.QtCore import QPoint
from PyQt5.QtTest import QSignalSpy
from canvas import Canvas
from libs.shape import Shape
from libs.utils import distance

class Test_CanvasFinalise:
    
    # For testing finalise method in case of same initial and final point
    @pytest.mark.smoke
    def test_finalise_operation_with_same_initial_and_final_point(self):
        # Arrange
        canvas = Canvas()
        canvas.current = Shape()
        canvas.current.points = [QPoint(0, 0), QPoint(0, 0)]
        # Act
        canvas.finalise()
        # Assert
        assert canvas.current is None, "Initial and final points are same, so current property should be None."

    # For testing finalise method in case the initial and final point are different
    @pytest.mark.regression
    def test_finalise_operation_with_different_initial_and_final_point(self):
        # Arrange
        canvas = Canvas()
        canvas.current = Shape()
        canvas.current.points = [QPoint(0, 0), QPoint(5, 5)]
        # Act
        canvas.finalise()
        # Assert
        assert canvas.current is None, "Upon finalising, current property should become None regardless of initial and final points"
        assert isinstance(canvas.shapes[0], Shape), "The shape created should be added to shapes property of Canvas instance"

    # For testing that hide_background gets disable after finalise operation
    @pytest.mark.regression
    def test_finalise_operation_hiding_state(self):
        # Arrange
        canvas = Canvas()
        canvas._hide_background = True
        canvas.current = Shape()
        canvas.current.points = [QPoint(0, 0), QPoint(5, 5)]
        # Act
        canvas.finalise()
        # Assert
        assert canvas._hide_background is False, "Upon finalising, hiding should be disabled."

    # For testing that upon finalise the signal to create new shape is emitted
    @pytest.mark.regression
    def test_finalise_operation_new_shape_signal(self):
        # Arrange
        canvas = Canvas()
        canvas.current = Shape()
        canvas.current.points = [QPoint(0, 0), QPoint(5, 5)]
        new_shape_signal_spy = QSignalSpy(canvas.newShape)
        # Act
        canvas.finalise()
        # Assert
        assert new_shape_signal_spy.wait(2000), "New shape signal should be emitted within 2000 microseconds"
