# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=hide_background_shapes_424d32e244
ROOST_METHOD_SIG_HASH=hide_background_shapes_a757b14dab


```
Scenario 1: Setting background hiding visibility
Details:
  TestName: test_set_background_visibility
  Description: This test will verify whether setting hide_background_shapes function to True indeed hides the background shapes.
Execution:
  Arrange: Create an instance of the Canvas class, add some shapes and select one of them.
  Act: Call the function hide_background_shapes with the parameter 'True'.
  Assert: Check that the background shapes are not visible.
Validation:
  It is important to ensure the correctness of the application's appearance. The successful hiding of the background shapes, when desired, confirms that the UI will be displayed correctly according to user interactions.

Scenario 2: No Hiding when no shape is selected
Details:
  TestName: test_no_hiding_without_shape
  Description: This test will ensure that if no shape is selected, none of the shapes are hidden, even when calling hide_background_shapes.
Execution:
  Arrange: Create an instance of the Canvas class, add several shapes but don't select any of them.
  Act: Call the function hide_background_shapes with the parameter 'True'.
  Assert: Check that the shapes are still visible.
Validation:
  It is critical to ensure that the application behaves correctly and doesn't hide shapes when none are selected. This ensures that the user can always select a shape.

Scenario 3: Changing the visibility status
Details:
  TestName: test_change_visibility_status
  Description: This test is focused on the ability of the method to toggle the hide state of the background shapes.
Execution:
  Arrange: Create an instance of the Canvas class, add several shapes, select one of them and set the hide state to True.
  Act: Call the function hide_background_shapes again but with parameter 'False'.
  Assert: Check that the background shapes become visible again.
Validation:
  It is important to ensure that the user can switch between hiding and showing of background shapes. This helps offer a flexible way to navigate the shapes within the application.

Scenario 4: Repaint after switch
Details:
  TestName: test_repaint_after_switch
  Description: This test is intended to ensure that after switching hiding state, the application repaints the Canvas.
Execution:
  Arrange: Create an instance of the Canvas class, add some shapes, select one of them and set the hide state to True.
  Act: Call the function hide_background_shapes again with parameter 'False'.
  Assert: Check whether the Canvas is repainted (presumably through a mocked repaint method).
Validation:
  The test assures that the UI is refreshed immediately after the hiding state changes, ensuring that the Canvas state shown to the user is always up-to-date.
```
"""

# ********RoostGPT********
# Test Cases:
import pytest
from canvas import Canvas
from libs.shape import Shape

class Test_CanvasHideBackgroundShapes:

    @pytest.mark.regression
    def test_set_background_visibility(self):
        canvas = Canvas()
        shape = Shape()
        canvas.shapes.append(shape)
        canvas.selected_shape = shape
        canvas.hide_background_shapes(True)
        assert canvas.hide_background is True
        assert canvas._hide_background is True

    @pytest.mark.regression
    def test_no_hiding_without_shape(self):
        canvas = Canvas()
        shape = Shape()
        canvas.shapes.append(shape)
        canvas.hide_background_shapes(True)
        assert canvas.hide_background is True
        assert canvas._hide_background is False

    @pytest.mark.regression
    def test_change_visibility_status(self):
        canvas = Canvas()
        shape = Shape()
        canvas.shapes.append(shape)
        canvas.selected_shape = shape
        canvas.hide_background_shapes(True)
        assert canvas.hide_background is True
        assert canvas._hide_background is True
        canvas.hide_background_shapes(False)
        assert canvas.hide_background is False
        assert canvas._hide_background is False

    @pytest.mark.regression
    def test_repaint_after_switch(self, mocker):
        mocker.patch.object(Canvas, 'repaint')
        canvas = Canvas()
        shape = Shape()
        canvas.shapes.append(shape)
        canvas.selected_shape = shape
        canvas.hide_background_shapes(True)
        canvas.hide_background_shapes(False)
        assert canvas.repaint.called is True

# Python Code Snippet (possibly within Canvas class):
    def hide_background_shapes(self, value):
        self.hide_background = value
        self.set_hiding(value)
        if self.selected_shape:
            # Only hide other shapes if there is a current selection.
            # Otherwise the user will not be able to select a shape.
            self.repaint()
    
    def set_hiding(self, enable=True):
        if self.selected_shape or not enable:
            self._hide_background = enable
        else:
            self._hide_background = False
