# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=addAction_b741b2dbee
ROOST_METHOD_SIG_HASH=addAction_ef9c87e93e


Scenario 1: Testing addAction when action is instance of QWidgetAction
Details:
  TestName: test_addAction_when_action_instance_of_QWidgetAction
  Description: This test is intended to verify that the addAction function correctly executes the parent's addAction method when the passed action instance is of QWidgetAction type.
Execution:
  Arrange: Initialize a Toolbar object and a QWidgetAction object.
  Act: Invoke the addAction method on the Toolbar object, passing the QWidgetAction object as the parameter.
  Assert: The expected outcome is that the super class' addAction method is called with the QWidgetAction instance.
Validation:
  The importance lies in the correct functioning of polymorphism whereby the parent's function is correctly invoked when the action passed is a QWidgetAction. This test assures that the QAction object is correctly handled.

Scenario 2: Testing addAction when action is not instance of QWidgetAction
Details:
  TestName: test_addAction_when_action_not_instance_of_QWidgetAction
  Description: This test checks the scenario where addAction is called with an action that isn't an instance of QWidgetAction.
Execution:
  Arrange: A Toolbar object is created and an action of any type other than QWidgetAction is defined.
  Act: The addAction method is called on the Toolbar object with the non-QWidgetAction object as the parameter.
  Assert: One should assert that a ToolButton object is created, the action is set as its default action and its style is set to the toolButtonStyle of the Toolbar. Finally, the ToolButton is added to the Toolbar.
Validation:
  This test ensures that when an action not of type QWidgetAction is passed, it is correctly encapsulated in a ToolButton. This maintains the integrity of the Toolbar by only accommodating appropriate type actions, meeting the function's requirements.

Scenario 3: Testing addAction when action is not provided 
Details:
  TestName: test_addAction_without_action
  Description: This test is intended to examine the function's behavior when no action is provided.
Execution:
  Arrange: Create an instance of Toolbar.
  Act: Invoke the addAction method on the Toolbar object without providing an action.
  Assert: Python should raise a TypeError indicating that addAction() is missing a required positional argument.
Validation:
  This test is important for ensuring the function requires an action to be passed, which is fundamental to the specifications and business requirements of the addAction function.
"""

# ********RoostGPT********
import pytest
from toolBar import ToolBar
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *

class Test_ToolBarAddAction:
    
    @pytest.mark.smoke
    def test_addAction_when_action_instance_of_QWidgetAction(self):
        # Arrange
        toolbar = ToolBar("Test")
        action = QWidgetAction(None)
        
        # Act
        result = toolbar.addAction(action)
        
        # Assert
        assert isinstance(result, QWidgetAction), "The returned object is not instance of QWidgetAction."

    @pytest.mark.regression
    def test_addAction_when_action_not_instance_of_QWidgetAction(self):
        # Arrange
        toolbar = ToolBar("Test")
        action = QAction()

        # Act
        toolbar.addAction(action)

        # Assert
        button = toolbar.layout().itemAt(toolbar.layout().count() -1).widget()
        assert isinstance(button, ToolButton), "The added widget is not instance of ToolButton"
        assert button.defaultAction() == action, "The ToolButton's default action is not the passed action"
        assert button.toolButtonStyle() == toolbar.toolButtonStyle(), "The ToolButton's style is not the toolbar's style"

    @pytest.mark.negative
    def test_addAction_without_action(self):
        # Arrange
        toolbar = ToolBar("Test")

        # Act & Assert
        with pytest.raises(TypeError):
            toolbar.addAction()
