# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=delete_selected_a27cff964f
ROOST_METHOD_SIG_HASH=delete_selected_f900ff3adc


Scenario 1: Test delete_selected when a shape is selected
Details:
  TestName: test_delete_selected_with_valid_shape
  Description: This test is intended to verify if the delete_selected function is able to successfully unhighlight and remove a selected shape from the shapes list.
Execution:
  Arrange: Initialize the Canvas with a few shapes. Set one of those shapes as selected_shape.
  Act: Invoke the delete_selected function.
  Assert: Verify that the selected_shape object has been removed from shapes list and selected_shape is set to None.
Validation:
  Ensuring the delete_selected method performs correctly is crucial for the functionalities of the Canvas that rely on deleting or editing shapes. This test verifies that the method is able to delete the selected shape as expected.

Scenario 2: Test delete_selected when no shape is selected
Details:
  TestName: test_delete_selected_with_no_shape
  Description: This test is intended to verify that the delete_selected function can handle cases where no shape is selected, i.e., selected_shape is None.
Execution:
  Arrange: Initialize the Canvas with a few shapes but do not set selected_shape.
  Act: Invoke the delete_selected function.
  Assert: Verify that the shapes list remains unchanged and selected_shape stays None.
Validation:
  This test is crucial as such scenarios may come up during the use of the Canvas, and it is important that they do not affect the Canvas functionality or induce crashes.

Scenario 3: Test delete_selected for its effect on other shapes
Details:
  TestName: test_delete_selected_effect_on_other_shapes
  Description: This test is intended to verify that the delete_selected function does not affect other shapes on the Canvas that are not selected.
Execution:
  Arrange: Initialize the Canvas with a few shapes and set one of them as selected_shape.
  Act: Invoke the delete_selected function.
  Assert: Verify that all other shapes aside from the selected_shape remain unchanged in the shapes list.
Validation:
  It is important to ensure that deletion of one shape does not impact others present in the Canvas. This test assesses the ability of the delete_selected function to perform isolated operations on the selected shape.

Scenario 4: Test the return value of delete_selected
Details:
  TestName:test_delete_selected_return_value
  Description: This test is intended to verify that the delete_selected function returns the deleted shape when a shape is selected.
Execution:
  Arrange: Initialize the Canvas with a few shapes and set one of them as selected_shape.
  Act: Call the delete_selected function and capture its return value.
  Assert: Verify that the return value is the same object as the one selected.
Validation:
  Ensuring the delete_selected method returns the correct object is vital, as this return value might be used in other areas of the application. This test validates the return behavior of the method.
"""

# ********RoostGPT********
import pytest
from canvas import Canvas #Assumed import path. Add exact path to Canvas module
from libs.shape import Shape #Assumed import path. Add exact path to Shape module

class Test_CanvasDeleteSelected:

    def test_delete_selected_with_valid_shape(self):
        #Create canvas and shape objects
        canvas = Canvas()
        shape = Shape()
        #Assign shapes to canvas
        canvas.shapes = [Shape(), shape, Shape()]
        #Assign one shape as selected_shape
        canvas.selected_shape = shape

        #Delete selected shape
        canvas.delete_selected()

        #Check if selected shape is deleted and no shape is currently selected
        assert shape not in canvas.shapes
        assert canvas.selected_shape is None

    def test_delete_selected_with_no_shape(self):
        #Create a canvas object and assign shapes to it
        canvas = Canvas()
        initial_shapes = [Shape(), Shape(), Shape()]
        canvas.shapes = initial_shapes[:]

        #Try to delete selected shape when no shape is selected
        canvas.delete_selected()

        #Check if no shape is deleted
        assert canvas.shapes == initial_shapes
        assert canvas.selected_shape is None

    def test_delete_selected_effect_on_other_shapes(self):
        #Create canvas and shape objects
        canvas = Canvas()
        shape1, shape2, shape3 = Shape(), Shape(), Shape()
        #Assign shapes and selected_shape to the canvas
        canvas.shapes = [shape1, shape2, shape3]
        canvas.selected_shape = shape2

        #Delete selected_shape
        canvas.delete_selected()

        #Check if only the selected_shape is removed 
        assert shape1 in canvas.shapes
        assert shape3 in canvas.shapes
        assert shape2 not in canvas.shapes

    def test_delete_selected_return_value(self):       
        #Create canvas and shape object
        canvas = Canvas()
        shape = Shape()
        #Assign shapes and selected_shape to canvas
        canvas.shapes = [Shape(), shape, Shape()]
        canvas.selected_shape = shape

        #Delete selected_shape and get returned shape
        deleted_shape = canvas.delete_selected()

        #Verify if deleted_shape is same as the one that was selected
        assert deleted_shape == shape
