# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=bnd_box_to_yolo_line_7f64fbe09d
ROOST_METHOD_SIG_HASH=bnd_box_to_yolo_line_eeecb2a170


Scenario 1: Verify Correctness of Box Conversion when Class Name Already Exists in the Class List
Details:
  TestName: test_bnd_box_to_yolo_line_existing_class
  Description: This test verifies that the function correctly converts a boundary box's position and dimensions into the format used by YOLO when the box's class is already present in the class list.
Execution:
  Arrange: Create an instance of the class, initialize a box dictionary with known values for xmin, xmax, ymin, ymax, and name (matching a name in the class list), and prepare a class list.
  Act: Call the function bnd_box_to_yolo_line, passing in the prepared box and class list.
  Assert: Check that the returned values match the expected class index, center position, width and height, as computed manually.
Validation:
  The purpose of this test is to ensure that the function's computation of a box's YOLO data is accurate when the box's class is already accounted for. This is a central part of the function's purpose and specification. 

Scenario 2: Verify Correctness of Box Conversion when Class Name Does Not Exist in the Class List
Details:
  TestName: test_bnd_box_to_yolo_line_new_class
  Description: This test verifies that the function correctly converts a boundary box's position and dimensions into the format used by YOLO, and correctly adds a new box's class to the class list.
Execution:
  Arrange: Create an instance of the class, initialize a box dictionary with known values for xmin, xmax, ymin, ymax, and name (not matching any name in the class list), and prepare a class list.
  Act: Call the function bnd_box_to_yolo_line, passing in the prepared box and class list.
  Assert: Check that the returned values match the expected class index, center position, width and height, as computed manually, and that the class list includes the new class.
Validation:
  The purpose of this test is to ensure that the function properly handles new box classes, both in terms of updating the class list and correctly computing the box's YOLO line. This is crucial for the function's flexibility and accuracy.

Scenario 3: Verify Behavior when Box Coordinates are Exactly on Image Boundaries
Details:
  TestName: test_bnd_box_to_yolo_line_on_boundaries
  Description: This test verifies that the function correctly handles the edge case where a box is positioned exactly at the image's boundaries, meaning xmin, ymin are 0 and xmax, ymax are equal to image's width and height.
Execution:
  Arrange: Create an instance of the class, initialize a box dictionary with values xmin, xmax equal to 0, image width and ymin, ymax equal to 0, image height, and prepare a class list.
  Act: Call the function bnd_box_to_yolo_line, passing in the prepared box and class list.
  Assert: Check that the returned values match the expected class index, center position (0.5, 0.5), width and height (1.0, 1.0).
Validation:
  This test verifies the function's handling of edge cases, and ensures that the function can accurately compute the position and dimensions even when the box aligns with the borders of the image.

"""

# ********RoostGPT********
import pytest
import codecs
import os
from yolo_io import YOLOWriter
from libs.constants import DEFAULT_ENCODING

pytestmark = pytest.mark.regression

class Test_YoloWriterBndBoxToYoloLine:

    @pytest.mark.positive
    def test_bnd_box_to_yolo_line_existing_class(self):
        yolo_writer = YOLOWriter('folder_name', 'filename', (100, 100))

        box = {'xmin': 10, 'xmax': 50, 'ymin': 20, 'ymax': 80, 'name': 'class1'}
        class_list = ['class1', 'class2']

        class_index, x_center, y_center, w, h = yolo_writer.bnd_box_to_yolo_line(box, class_list)

        assert class_index == 0
        assert x_center == 0.3
        assert y_center == 0.5
        assert w == 0.4
        assert h == 0.6

    @pytest.mark.positive
    def test_bnd_box_to_yolo_line_new_class(self):
        yolo_writer = YOLOWriter('folder_name', 'filename', (100, 100))

        box = {'xmin': 10, 'xmax': 50, 'ymin': 20, 'ymax': 80, 'name': 'class3'}
        class_list = ['class1', 'class2']

        class_index, x_center, y_center, w, h = yolo_writer.bnd_box_to_yolo_line(box, class_list)

        assert class_index == 2
        assert x_center == 0.3
        assert y_center == 0.5
        assert w == 0.4
        assert h == 0.6
        assert 'class3' in class_list

    @pytest.mark.negative
    def test_bnd_box_to_yolo_line_on_boundaries(self):
        yolo_writer = YOLOWriter('folder_name', 'filename', (100, 100))

        box = {'xmin': 0, 'xmax': 100, 'ymin': 0, 'ymax': 100, 'name': 'class1'}
        class_list = ['class1', 'class2']

        class_index, x_center, y_center, w, h = yolo_writer.bnd_box_to_yolo_line(box, class_list)

        assert class_index == 0
        assert x_center == 0.5
        assert y_center == 0.5
        assert w == 1.0
        assert h == 1.0
