# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_shape_0467ac60e4
ROOST_METHOD_SIG_HASH=add_shape_ac27a525ae


```
Scenario 1: Test adding valid shape with correct boundaries
Details:
  TestName: test_add_shape_valid
  Description: This test will verify that the add_shape function correctly calculates the points of a shape based on the given boundary coordinates. 
Execution:
  Arrange: Create an instance of the class with necessary parameters, and prepare a boundary box object with numeric "x", "y", "width", and "height" keys.
  Act: Call the add_shape function on the instance, passing label and boundary box as parameters.
  Assert: Check that the shape is added properly to the shapes list with calculated points.
Validation:
  Rationalize: This test is important to ensure that the system correctly constructs the shape and prepares it for further operations.

Scenario 2: Test adding shape when x, y, width and height are equal to 0
Details:
  TestName: test_add_shape_zero_boundary
  Description: This test will verify that the add_shape function correctly handles a scenario where all parameters of the boundary box (x, y, width, height) are set to 0. 
Execution:
  Arrange: Create an instance of the class with necessary parameters, and define a boundary box object where all values are set to 0.
  Act: Call the add_shape function on the instance, passing label and the zero-value boundary box as parameters.
  Assert: Check whether shapes are added to the list of shapes with a proper structure, but with all points equal to (0, 0).
Validation:
  Rationalize: This test is crucial to ensure the system can handle edge case scenarios and return valid shapes even if the original boundary box parameters are configured to be 0.

Scenario 3: Check the shape's structure after it is added
Details:
  TestName: test_shape_structure
  Description: The test will verify that the structure of the added shape meets the expected format (Label, Points, None, None, True).
Execution:
  Arrange: Generate an instance of the class with required parameters, and prepare a valid boundary box.
  Act: Call the add_shape function on the instance, passing label and boundary box as parameters.
  Assert: Confirm that shapes are correctly added and that the structure of the shape includes correct points, label and other parameters in the expected order and type.
Validation:
  Rationalize: This helps to ensure the integrity of the shape data structure, which could affect downstream processes such as visualization or further geometrical calculations.

Scenario 4: Test behavior when negative boundary values are provided
Details:
  TestName: test_negative_boundary_values
  Description: This test will confirm the add_shape functionality when the boundary box contains negative values.
Execution:
  Arrange: Generate an instance of the class with appropriate parameters, and then create a boundary box where "x", "y", "width", and "height" have negative values.
  Act: Call the add_shape function with the label and the negative-value boundary box as parameters.
  Assert: Check that the shapes are added with shape points properly calculated (keeping in mind that the "x" and "y" points may result in different negative values due to width/height division).
Validation:
  Rationalize: This check is needed to ensure that the unit under test can handle negative values in the bounding box, which might come from user input or from calculated values in a certain application context.
```
"""

# ********RoostGPT********
import pytest
import json
from pathlib import Path
from libs.constants import DEFAULT_ENCODING
import os

from create_ml_io import CreateMLReader 

@pytest.mark.regression
class Test_CreateMlReaderAddShape:
    def setup_class(self):
        self.reader = CreateMLReader('folder', 'file', (128, 128, 3), [], 'output')

    @pytest.mark.positive
    def test_add_shape_valid(self):
        boundary_box = {"x": 10, "y": 20, "width": 60, "height": 80}
        self.reader.add_shape('label1', boundary_box)
        
        assert len(self.reader.shapes) == 1
        shape = self.reader.shapes[0]
        assert shape[0] == 'label1'
        assert shape[1] == [(0,10), (30,10), (30,-30), (0,-30)]
        
    @pytest.mark.negative
    def test_add_shape_zero_boundary(self):
        boundary_box = {"x": 0, "y": 0, "width": 0, "height": 0}
        self.reader.add_shape('label2', boundary_box)

        assert len(self.reader.shapes) == 2
        shape = self.reader.shapes[1]
        assert shape[0] == 'label2'
        assert shape[1] == [(0,0), (0,0), (0,0), (0,0)]

    @pytest.mark.smoke
    def test_shape_structure(self):
        boundary_box = {"x": 10, "y": 20, "width": 30, "height": 40}
        self.reader.add_shape('label3', boundary_box)

        assert len(self.reader.shapes) == 3
        shape = self.reader.shapes[2]
        assert shape[0] == 'label3'
        assert isinstance(shape[1], list)
        assert shape[1][0][0] == -5

    @pytest.mark.valid
    def test_negative_boundary_values(self):
        boundary_box = {"x": -10, "y": -20, "width": -30, "height": -40}
        self.reader.add_shape('label4', boundary_box)

        assert len(self.reader.shapes) == 4
        shape = self.reader.shapes[3]
        assert shape[0] == 'label4'
        assert isinstance(shape[1], list)
        assert shape[1][0][0] == -25
        assert shape[1][0][1] == -30
