# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=bounding_rect_f3812ea11d
ROOST_METHOD_SIG_HASH=bounding_rect_8f37da1ede


Scenario 1: Test bounding rectangle function with valid path
Details:
  TestName: test_bounding_rect_valid_path
  Description: This test aims to verify the bounding rectangle function when a valid path is provided.
Execution:
  Arrange: Initialize an instance of the class providing valid arguments. Create a path with data points.
  Act: Invoke the bounding_rect function on the initialized object.
  Assert: Expected to return a QRectF object representing the bounding rectangle of the path.
Validation:
  This test is crucial as it validates the core functionality of creating a bounding rectangle given a specific path. A successful pass means that the bounding rectangle is correctly evaluated, ensuring accurate geometric analysis and data visualization.

Scenario 2: Test bounding rectangle function with an empty path
Details:
  TestName: test_bounding_rect_empty_path
  Description: This test validates the bounding rectangle function when an empty path is given.
Execution:
  Arrange: Initialize an instance of the class providing valid arguments but do not add any points to the path.
  Act: Invoke the bounding_rect function on the initialized object.
  Assert: Expected to return an empty QRectF object as there are no data points.
Validation:
  This test ensures that the bounding rectangle function can handle cases where there are no data points to analyze. This ensures the robustness of the function in various scenarios.

Scenario 3: Test bounding rectangle function where path contains a single point
Details:
  TestName: test_bounding_rect_single_point
  Description: This test verifies the bounding rectangle function when the path only contains a single point.
Execution:
  Arrange: Initialize an instance of the class providing valid arguments. Add a single point to the path.
  Act: Invoke the bounding_rect function on the initialized object.
  Assert: It is expected to return a QRectF object that corresponds to the exact location of the single point.
Validation:
  A test is essential to confirm that the function works correctly even when the path is reduced to a single point.

Scenario 4: Test bounding rectangle function where path forms an irregular shape
Details:
  TestName: test_bounding_rect_irregular_shape
  Description: This test validates the bounding rectangle function when the path forms an irregular shape.
Execution:
  Arrange: Initialize an instance of the class providing valid arguments. Add multiple points to the path in such a way that an irregular shape is formed.
  Act: Invoke the bounding_rect function on the initialized object.
  Assert: It is expected to return a QRectF object that appropriately covers the full extent of the irregular shape.
Validation:
  This test is important to confirm that the function can handle complex data models and accurately identify the bounding rectangle, irrespective of the irregularity in the shape.

"""

# ********RoostGPT********
import pytest
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from libs.utils import distance
from shape import Shape

class Test_ShapeBoundingRect:
    
    @pytest.mark.regression
    def test_bounding_rect_valid_path(self):
        shape = Shape()
        shape.points = [QPoint(0, 0), QPoint(10, 10), QPoint(-10, -10)]
        bounding_rect = shape.bounding_rect()
        assert isinstance(bounding_rect, QRectF)
        assert bounding_rect.topLeft() == QPointF(-10, -10)
        assert bounding_rect.bottomRight() == QPointF(10, 10)

    @pytest.mark.regression
    def test_bounding_rect_empty_path(self):
        shape = Shape()
        bounding_rect = shape.bounding_rect()
        assert isinstance(bounding_rect, QRectF)
        assert bounding_rect.isNull()

    @pytest.mark.regression
    def test_bounding_rect_single_point(self):
        shape = Shape()
        shape.points = [QPoint(0, 0)]
        bounding_rect = shape.bounding_rect()
        assert isinstance(bounding_rect, QRectF)
        assert bounding_rect.topLeft() == QPointF(0, 0)
        assert bounding_rect.bottomRight() == QPointF(0, 0)

    @pytest.mark.regression
    def test_bounding_rect_irregular_shape(self):
        shape = Shape()
        shape.points = [QPoint(5, 5), QPoint(10, 10), QPoint(0, 0), QPoint(-10, -10)]
        bounding_rect = shape.bounding_rect()
        assert isinstance(bounding_rect, QRectF)
        assert bounding_rect.topLeft() == QPointF(-10, -10)
        assert bounding_rect.bottomRight() == QPointF(10, 10)
