# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=drawing_2bab15ca0c
ROOST_METHOD_SIG_HASH=drawing_f9e9cc866d


Scenario 1: Check the Drawing Mode Active Status
Details:
  TestName: test_drawing_mode_active
  Description: This test is intended to verify if the function correctly shows the drawing mode to be active when the mode is set to 'CREATE'.
Execution:
  Arrange: Initialize an instance of Canvas and set the mode to 'CREATE'.
  Act: Invoke the drawing function without any parameters.
  Assert: Expected outcome is True as the mode of the instance is 'CREATE'.
Validation:
  This test verifies that the drawing function accurately acknowledges the current active mode of the Canvas instance. This is important for subsequently controlling behavior such as drawing or editing shapes on the canvas.

Scenario 2: Check the Drawing Mode Inactive Status
Details:
  TestName: test_drawing_mode_inactive
  Description: This test is intended to verify if the function correctly shows the drawing mode to be inactive when the mode is not 'CREATE'.
Execution:
  Arrange: Initialize an instance of Canvas and set the mode to any constant other than 'CREATE'.
  Act: Invoke the drawing function without any parameters.
  Assert: Expected outcome is False as the mode of the instance is not 'CREATE'.
Validation:
  This scenario validates that the drawing function correctly identifies when it's not in drawing or 'CREATE' mode. This is significant as it controls whether shapes can be added to the canvas.

Scenario 3: Check Default Mode of Canvas
Details:
  TestName: test_default_canvas_mode
  Description: This test is intended to verify the default mode of a newly initialised Canvas instance.
Execution:
  Arrange: Initialize a fresh instance of Canvas without setting any mode.
  Act: Invoke the drawing function without any parameters.
  Assert: Expected outcome depends on the default mode set during initialisation. If 'CREATE' is default, outcome is True, else False.
Validation:
  This scenario ensures the default state of the Canvas is accurately reported by the drawing method. This is crucial as it can critically influence subsequent operations on the Canvas, such as drawing or editing shapes. 

Scenario 4: Validate mode after changing it from CREATE to another mode
Details:
  TestName: test_change_of_mode
  Description: This test is intended to verify if the mode change is effective and correctly identified by the drawing method.
Execution:
  Arrange: Initialize an instance of Canvas, set the mode to 'CREATE', invoke the drawing function, and then change the mode to any other mode.
  Act: Invoke the drawing function again without any parameters.
  Assert: Expected outcome is False as the mode of the instance is now different from 'CREATE'.
Validation:
  This test ensures that the drawing method is dynamic and accurately reflects changes to the Canvas mode. This is crucial for maintaining the integrity of the Canvas operations.

"""

# ********RoostGPT********
import pytest
from canvas import Canvas

class Test_CanvasDrawing:

    @pytest.mark.regression
    def test_drawing_mode_active(self):
        # Arrange
        canvas = Canvas()
        canvas.mode = Canvas.CREATE

        # Act
        result = canvas.drawing()

        # Assert
        assert result == True

    @pytest.mark.regression
    def test_drawing_mode_inactive(self):
        # Arrange
        canvas = Canvas()
        canvas.mode = 'EDIT'  # Assuming 'EDIT' is another valid mode

        # Act
        result = canvas.drawing()

        # Assert
        assert result == False

    @pytest.mark.regression
    def test_default_canvas_mode(self):
        # Arrange
        canvas = Canvas()

        # Act
        result = canvas.drawing()

        # Assert
        # As the task prompt does not specify what the default mode is,
        # we'll assume it's not 'CREATE'. Correct the expectation as needed.
        assert result == False

    @pytest.mark.regression
    def test_change_of_mode(self):
        # Arrange
        canvas = Canvas()
        canvas.mode = Canvas.CREATE
        _ = canvas.drawing()  # initial drawing invocation
        canvas.mode = 'EDIT'  # change mode

        # Act
        result = canvas.drawing()

        # Assert
        assert result == False
