# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=save_bf99c8f3e5
ROOST_METHOD_SIG_HASH=save_315ff9f749


Scenario 1: Testing Functionality of save method with specified target_file
Details:
  TestName: test_save_method_with_target_file
  Description: This test is focused on the business logic of specifying a target_file while saving. The assumption is if a target_file is specified, the system would save the file to the specified path.
Execution:
  Arrange: An instance of the class would be created with necessary parameters like folder_name, filename, and img_size.
  Act: Call the save function with target_file as parameter to act as the destination of the newly saved file.
  Assert: The desired outcome is that the out_file should correspond to the target_file specified, and method should successfully write and save the file to the specified path.
Validation:
  It’s crucial to ensure that the function is able to handle user specified paths. File saving needs to be as user-specific as possible, and thus it’s necessary to assert that this function works as intended.

Scenario 2: Testing undefined target_file
Details:
  TestName: test_default_save_location
  Description: This test verifies the business logic of saving a file when no target file is specified.
Execution:
  Arrange: Create an instance of the class with necessary parameters.
  Act: Call the save function without providing any target_file as a parameter.
  Assert: The assert will check if the function successfully saves the file to the default filename location, defined by self.filename + XML_EXT.
Validation:
  The test is important to ensure the module-level assignment XML_EXT works properly with the filename, and that the save method successfully uses these as a default location.

Scenario 3: Checking the writing of data to file
Details:
  TestName: test_writing_to_file
  Description: This test validates on whether the data is correctly written to the file.
Execution:
  Arrange: Instantiate the class with required parameters.
  Act: Call save method and let it write to the output file.
  Assert: Check if the written data in the file is the same as the prettyfied xml data that was generated.
Validation:
  To ensure the data integrity and data saving is correctly implemented, this test scenario is crucial. Correct storage of this data is key to maintaining data across uses of the application.

Scenario 4: Testing the utf8 decoding 
Details:
  TestName: test_utf8_decoding
  Description: This test would be checking if output data is correctly decoded in 'utf8' before being written to the output file.
Execution:
  Arrange: Initialize the class with required parameters.
  Act: Call save method and let it write to the output file.
  Assert: Check if the decoded data can be successfully transformed back to the original data.
Validation:
  Given that the function uses utf8 encoding, this test is vital to confirm the consistency and integrity of data after it has been decoded and saved in the file. The decoding logic should not alter the structure or meaning of the original data.
"""

# ********RoostGPT********
import sys
import pytest
from xml.etree import ElementTree
from xml.etree.ElementTree import Element, SubElement
from lxml import etree
import codecs
from libs.constants import DEFAULT_ENCODING
from libs.ustr import ustr
from pascal_voc_io import PascalVocWriter

class Test_PascalVocWriterSave:
    
    folder_name = "test_folder"
    filename = "test_filename"
    img_size = (100,100,3)
    
    @pytest.mark.regression
    def test_save_method_with_target_file(self):
        target_file = "test_target_file.xml"
        writer = PascalVocWriter(self.folder_name, self.filename, self.img_size)
        writer.save(target_file)
        assert target_file in sys.modules

    @pytest.mark.regression
    def test_default_save_location(self):
        writer = PascalVocWriter(self.folder_name, self.filename, self.img_size)
        writer.save()
        default_filename = self.filename + ".xml"
        assert default_filename in sys.modules

    @pytest.mark.regression
    def test_writing_to_file(self):
        writer = PascalVocWriter(self.folder_name, self.filename, self.img_size)
        writer.save()
        default_filename = self.filename + ".xml"
        with open(default_filename, "r") as file:
            data = file.read()
        assert data == writer.prettify(writer.gen_xml()).decode('utf8')

    @pytest.mark.regression
    def test_utf8_decoding(self):
        writer = PascalVocWriter(self.folder_name, self.filename, self.img_size)
        writer.save()
        default_filename = self.filename + ".xml"
        with open(default_filename, "r") as file:
            data = file.read().encode('utf8')
        assert data == writer.prettify(writer.gen_xml())
