# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=transform_pos_abfe16eec0
ROOST_METHOD_SIG_HASH=transform_pos_40848288af


Scenario 1: Verifying transformation of widget-logical coordinates to painter-logical coordinates with positive integer inputs
Details:
  TestName: test_transform_pos_positive_int
  Description: This test checks if the function correctly performs the transformation when positive integer values are passed as a point parameter to the transform_pos function.
Execution:
  Arrange: Prepare a positive integer point, let's say QPointF(10, 10), and initial canvas with some scale and offset values.
  Act: Invoke transform_pos function with the prepared point as parameter.
  Assert: Check if the transformed x and y values are as expected (i.e., point/scale - offset).
Validation:
  This test verifies that the transform_pos function successfully transforms widget-logical coordinates to painter-logical coordinates for positive integers, which is essential for the correct positioning of graphical elements on the canvas.

Scenario 2: Verifying transformation with zero point input
Details:
  TestName: test_transform_pos_zero_input
  Description: This test evaluates the function's behavior given zero coordinate inputs.
Execution:
  Arrange: Prepare a point with zero coordinates (i.e., QPointF(0, 0)) and initial canvas with some scale and offset values.
  Act: Invoke transform_pos function with the zero coordinate point as a parameter.
  Assert: Assert that the transformed x and y values match the offset divided by scale with a negative sign, as per the formula (0/scale - offset).
Validation:
  This test verifies the transformation with zero as an input, which is crucial for boundary conditions and ensuring correct transformation near the origin of axes.

Scenario 3: Verifying transformation with floating point inputs
Details:
  TestName: test_transform_pos_float_input
  Description: This test verifies the successful transformation of widget-logical coordinates to painter-logical coordinates, taking floating point numbers as inputs.
Execution:
  Arrange: Create a floating point point (e.g., QPointF(3.5, 2.7)) and initial canvas with some scale and offset values.
  Act: Invoke transform_pos function by passing the floating point coordinate as an argument.
  Assert: Confirm that the transformed x and y values match the expectation as per the transformation rule (point/scale - offset).
Validation:
  This realistic scenario broadens the test coverage by ensuring that the transform_pos function can handle floating point numbers correctly, ultimately contributing to depiction precision.

Scenario 4: Verifying negative point input transformation
Details:
  TestName: test_transform_pos_negative_input
  Description: This test checks the transformation for negative integers input for the point's x and y coordinates.
Execution:
  Arrange: Create a negative point (e.g., QPointF(-5, -10)) and initial canvas with some scale and offset values.
  Act: Call the transform_pos function by passing the negative coordinate point as an argument.
  Assert: Assert that the transformed x and y values match the expectation based on the transformation formula (point/scale - offset).
Validation:
  This test helps ensure the transformation function's efficacy in handling negative point inputs, which could occur depending on the canvas's relative movement or positioning.
"""

# ********RoostGPT********
import pytest
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from canvas import Canvas


class Test_CanvasTransformPos:

    @pytest.mark.positive
    def test_transform_pos_positive_int(self):
        canvas = Canvas()
        canvas.scale = 2.0
        point = QPointF(10, 10)

        result = canvas.transform_pos(point)

        expected_x = point.x() / canvas.scale - canvas.offset_to_center().x()
        expected_y = point.y() / canvas.scale - canvas.offset_to_center().y()
        assert result.x() == expected_x
        assert result.y() == expected_y

    @pytest.mark.boundary
    def test_transform_pos_zero_input(self):
        canvas = Canvas()
        canvas.scale = 2.0
        point = QPointF(0, 0)

        result = canvas.transform_pos(point)

        expected_x = point.x() / canvas.scale - canvas.offset_to_center().x()
        expected_y = point.y() / canvas.scale - canvas.offset_to_center().y()
        assert result.x() == expected_x
        assert result.y() == expected_y

    @pytest.mark.positive
    def test_transform_pos_float_input(self):
        canvas = Canvas()
        canvas.scale = 2.0
        point = QPointF(3.5, 2.7)

        result = canvas.transform_pos(point)

        expected_x = point.x() / canvas.scale - canvas.offset_to_center().x()
        expected_y = point.y() / canvas.scale - canvas.offset_to_center().y()
        assert result.x() == expected_x
        assert result.y() == expected_y

    @pytest.mark.negative
    def test_transform_pos_negative_input(self):
        canvas = Canvas()
        canvas.scale = 2.0
        point = QPointF(-5, -10)

        result = canvas.transform_pos(point)

        expected_x = point.x() / canvas.scale - canvas.offset_to_center().x()
        expected_y = point.y() / canvas.scale - canvas.offset_to_center().y()
        assert result.x() == expected_x
        assert result.y() == expected_y

