# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=copy_baeebe1c3e
ROOST_METHOD_SIG_HASH=copy_c499033b3b


Scenario 1: Test Copy method to validate copied shape characteristics
Details:
  TestName: test_copy_validates_shape_attributes
  Description: This test is intended to verify if the copied shape carries same 'label', 'fill', 'selected' and 'closed' attributes as the original shape.
Execution:
  Arrange: Initialize an object with specific properties for label, fill, selected and closed.
  Act: Invoke the copy function on the object.
  Assert: The copied object should have the same values for label, fill, selected and closed attributes as the original shape object.
Validation:
  This test is important as it confirms the core functionality of the copy method in retaining major attributes of the shape object.

Scenario 2: Test Copy method to validate point duplication
Details:
  TestName: test_copy_validates_point_duplication
  Description: This test is intended to check whether the points in the copied shape are the same as those in the original shape.
Execution:
  Arrange: Initialize a shape object with specific points.
  Act: Invoke the copy method for the created object.
  Assert: The copied object should have the same points as the original shape object.
Validation:
  The significance of this test lies in confirming that the copy method duplicates points correctly, maintaining the structure and position of the shape.

Scenario 3: Test Copy method to validate line color retention
Details:
  TestName: test_copy_validates_line_color_retention
  Description: This test is designed to verify whether the copied shape retains the customized line color of the shape.
Execution:
  Arrange: Initialize a shape object with a distinct line color.
  Act: Use the copy method to produce a copy of the shape object.
  Assert: The line color of the copied object should match that of the initial shape object.
Validation:
  This test ensures that the copy method retains visually relevant features such as line color, which is crucial for maintaining consistent user experience.

Scenario 4: Test Copy method to validate fill color retention
Details:
  TestName: test_copy_validates_fill_color_retention
  Description: This test is intended to verify that the copied shape maintains the customized fill color of the shape.
Execution:
  Arrange: Create a shape object with a specific fill color.
  Act: Invoke the copy function on the initial shape object.
  Assert: The fill color in the copied shape object should be the same as in the original shape object.
Validation:
  This test is essential for ensuring that the copy method correctly keeps visual features like fill color, crucial for user experience consistency when dealing with duplicated shapes.

Scenario 5: Test Copy method to validate difficult attribute
Details:
  TestName: test_copy_validates_difficult_attribute
  Description: This test is intended to verify whether the copied shape keeps the 'difficult' attribute value of the shape.
Execution:
  Arrange: Initialize a shape object with the 'difficult' attribute set to a specific value.
  Act: Invoke the copy function on this initialized shape object.
  Assert: The copied shape object should have the same 'difficult' attribute value as the original shape object.
Validation:
  This test is crucial as the 'difficult' attribute may influence how a shape is processed or displayed, and its continuity needs to be preserved in copies.
"""

# ********RoostGPT********
import pytest
from shape import Shape
from PyQt5.QtGui import QColor

class Test_ShapeCopy:
    
    @pytest.mark.core
    def test_copy_validates_shape_attributes(self):
        original_shape = Shape('rectangle', difficult=True)
        original_shape.fill = True
        original_shape.selected = True
        original_shape._closed = True

        copied_shape = original_shape.copy()

        assert copied_shape.label == original_shape.label
        assert copied_shape.fill == original_shape.fill
        assert copied_shape.selected == original_shape.selected
        assert copied_shape._closed == original_shape._closed
        assert copied_shape.difficult == original_shape.difficult
    
    @pytest.mark.core
    def test_copy_validates_point_duplication(self):
        original_shape = Shape('rectangle')
        original_shape.points = [(10,10), (20,20), (30,30)]

        copied_shape = original_shape.copy() 

        assert copied_shape.points == original_shape.points

    @pytest.mark.visual
    def test_copy_validates_line_color_retention(self):
        original_shape = Shape('rectangle', line_color=QColor(100, 150, 200))

        copied_shape = original_shape.copy()

        assert copied_shape.line_color == original_shape.line_color

    @pytest.mark.visual
    def test_copy_validates_fill_color_retention(self):
        original_shape = Shape('rectangle')
        original_shape.fill_color = QColor(100, 150, 200)

        copied_shape = original_shape.copy()
        
        assert copied_shape.fill_color == original_shape.fill_color

    @pytest.mark.attribute
    def test_copy_validates_difficult_attribute(self):
        original_shape = Shape('rectangle', difficult=True)

        copied_shape = original_shape.copy()

        assert copied_shape.difficult == original_shape.difficult
