# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=end_move_48708cabbb
ROOST_METHOD_SIG_HASH=end_move_104935bc27


Scenario 1: Copy selected shape
Details:
  TestName: test_end_move_with_copy
  Description: This should test the logic of the end_move method given the copy parameter is set to True. This would create a copy of the selected shape.
Execution:
  Arrange: Instantiate the class and set the internal state by setting selected_shape and selected_shape_copy.
  Act: Run end_move with the copy parameter set as True.
  Assert: Verify if a shape was added into the shapes array, the previous shape is unselected, and the selected shape is updated.
Validation:
  This scenario verifies that copying shapes works as expected. If the test passes, we can be confident that the end_move method accurately handles the duplication.

Scenario 2: Move selected shape
Details:
  TestName: test_end_move_without_copy
  Description: This should test the logic of the end_move method given the copy parameter is set to False. This would move the selected shape.
Execution:
  Arrange: Instantiate the class and set the internal state by setting selected_shape and selected_shape_copy.
  Act: Run end_move with the copy parameter set as False.
  Assert: Verify if the points of the selected shape are updated to the copied shape's points.
Validation:
  This scenario verifies that the end_move supports shape moving operation. The successful passing of this test ensures that the moving feature works as expected.

Scenario 3: No selected shape copy to move
Details:
  TestName: test_end_move_with_no_selected_shape_copy
  Description: This should test the logic of the end_move method when selected_shape_copy is not present.
Execution:
  Arrange: Instantiate the class and set the internal state by setting selected_shape but not setting selected_shape_copy.
  Act: Run end_move regardless of the copy parameter value.
  Assert: This would likely raise an assertion error. Catch this error and assert the error was raised
Validation:
  This is an edge case scenario that validates that the end_move method correctly asserts the presence of both selected_shape and selected_shape_copy.

Scenario 4: No selected shape to move
Details:
  TestName: test_end_move_with_no_selected_shape
  Description: This should test the logic of the end_move method when selected_shape is not present.
Execution:
  Arrange: Instantiate the class and set the internal state by setting selected_shape_copy but not setting selected_shape.
  Act: Run end_move regardless of the copy parameter value.
  Assert: This would likely raise an assertion error. Catch this error and assert the error was raised
Validation:
  This is an edge case scenario that verifies the end_move method correctly asserts the presence of the selected_shape for moving functionality.
"""

# ********RoostGPT********
    def end_move(self, copy=False):
        if not self.selected_shape or not self.selected_shape_copy:
            raise ValueError("Both selected_shape and selected_shape_copy should be non-None objects.")
        
        shape = self.selected_shape_copy
        # del shape.fill_color
        # del shape.line_color
        if copy:
            self.shapes.append(shape)
            self.selected_shape.selected = False
            self.selected_shape = shape
            self.repaint()
        else:
            self.selected_shape.points = [p for p in shape.points]
        self.selected_shape_copy = None
