# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=offset_to_center_3ea2fd27aa
ROOST_METHOD_SIG_HASH=offset_to_center_b3d8af4977


Scenario 1: Validating the center offset when pixmap area is larger than the Canvas size
Details:
  TestName: test_offset_when_pixmap_larger
  Description: This test is intended to verify the offset calculation when the pixmap's height and width (scaled by self.scale) are larger than the area of the Canvas.
Execution:
  Arrange: Initialize a Canvas object with a large pixmap size and a smaller area size. Set self.scale appropriately.
  Act: Invoke the function offset_to_center.
  Assert: Check the returned offset. Both x and y values should be zero as per the function's logic.
Validation:
  The test ensures that the function properly handles cases when the scaled pixmap size exceeds the Canvas size, returning an offset of zero.

Scenario 2: Validating the center offset when Canvas area is larger than the pixmap size
Details:
  TestName: test_offset_when_canvas_larger
  Description: This test is intended to verify the offset calculation when Canvas's area is larger than the pixmap's height and width (scaled by self.scale).
Execution:
  Arrange: Initialize a Canvas object with a small pixmap size and a larger area size. Set self.scale appropriately.
  Act: Invoke the function offset_to_center.
  Assert: Check the returned offset. Both x and y values should be positive as per the function's logic.
Validation:
  This test validates that the function accurately calculates the offset for centering when the Canvas area is larger than the pixmap's size.

Scenario 3: Validating the center offset when pixmap and Canvas are equal in size
Details:
  TestName: test_offset_when_equal_sizes
  Description: This test verifies the offset calculation when the pixmap's height and width (scaled by self.scale) is equal to the canvas's area.
Execution:
  Arrange: Initialize a Canvas instance with equal pixmap size and area size. Set self.scale to 1.
  Act: Invoke the function offset_to_center.
  Assert: Check the returned offset. Both x and y values should be zero as per the function's logic.
Validation:
  This test ensures the function accurately handles cases when the pixmap's size matches the Canvas area, producing an offset value of zero.

Scenario 4: Validate the center offset when the area or pixmap dimensions are zero
Details:
  TestName: test_offset_with_zero_dimensions
  Description: This test will validate if function can properly handle cases where either the pixmap or canvas size contains a zero dimension.
Execution:
  Arrange: Initialize a Canvas with one of the sizes or dimensions being zero.
  Act: Invoke the function offset_to_center.
  Assert: Check the returned offset. If one of the dimensions of the Canvas or pixmap is zero, the corresponding value of the returned offset should also be zero.
Validation:
  This test is important to ensure the function handles special edge cases where zero dimensions may be involved, preventing potential division by zero errors.
"""

# ********RoostGPT********
import pytest
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *

class TestCanvasOffsetToCenter:
    @pytest.fixture(autouse=True)
    def setup_class(self):
        self.canvas = Canvas()
    
    def test_offset_when_pixmap_larger(self):
        self.canvas.pixmap = QPixmap(500, 500)
        self.canvas.scale = 2
        offset = self.canvas.offset_to_center()
        assert offset.x() == 0
        assert offset.y() == 0

    def test_offset_when_canvas_larger(self):
        self.canvas.pixmap = QPixmap(50, 50)
        self.canvas.scale = 0.5
        offset = self.canvas.offset_to_center()
        assert offset.x() > 0
        assert offset.y() > 0

    def test_offset_when_equal_sizes(self):
        self.canvas.pixmap = QPixmap(100, 100)
        self.canvas.scale = 1
        offset = self.canvas.offset_to_center()
        assert offset.x() == 0
        assert offset.y() == 0

    def test_offset_with_zero_dimensions(self):
        self.canvas.pixmap = QPixmap(0, 100)
        offset = self.canvas.offset_to_center()
        assert offset.x() == 0
        assert offset.y() == 0

        self.canvas.pixmap = QPixmap(100, 0)
        offset = self.canvas.offset_to_center()
        assert offset.x() == 0
        assert offset.y() == 0
