# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=set_editing_940db1c848
ROOST_METHOD_SIG_HASH=set_editing_1bb4cfeac7


Scenario 1: Test if editing mode is correctly set when value equals True
Details:
  TestName: test_set_editing_mode_true
  Description: The test is intended to verify if the editing mode is set correctly when the parameter passed is True.
Execution:
  Arrange: Create an instance of the Class and assign it to a variable. 
  Act: Call the set_editing method on the instance variable created in the Arrange stage, passing True as the parameter.
  Assert: Check if the expected outcome that mode is EDIT.
Validation:
  This test is essential as it verifies if the application correctly switches to editing mode when requested, which is crucial for the correct functioning of the application.

Scenario 2: Test if creation mode is correctly set when value equals False
Details:
  TestName: test_set_editing_mode_false
  Description: The test is intended to verify if the creation mode is set correctly when the parameter passed is False.
Execution:
  Arrange: Create an instance of the Class and assign it to a variable.
  Act: Call the set_editing method on the instance variable created in the Arrange stage, passing False as the parameter.
  Assert: Check if the expected outcome that mode is CREATE and methods un_highlight and de_select_shape are called.
Validation:
  This test guarantees that the application can correctly transition from the editing mode to create mode, which is a fundamental feature of this application.

Scenario 3: Test if prev_point resets on set_editing invocation
Details:
  TestName: Test_prev_point_reset_on_set_editing
  Description: The test will verify if set_editing method resets 'prev_point'
Execution:
  Arrange: Create an instance of the Class, set a value for 'prev_point', and assign it to a variable.
  Act: Call the set_editing method on the instance variable.
  Assert: Check if 'prev_point' successfully resets to an empty QPointF object.
Validation: 
  This test assists in confirming whether the 'prev_point' property reset operation works correctly. Providing a clean slate to start the next operation is necessary for proper object behaviour.

Scenario 4: Check if repaint() is called after set_editing()
Details:
  TestName: test_repaint_invocation_on_set_editing
  Description: This test will verify if repaint() method is called after set_editing() method.
Execution:
  Arrange: Create a mock for repaint() function and an instance of the class.
  Act: Call the set_editing method on the instance.
  Assert: Check if repaint() mock function is called.
Validation:
  It ensures that the application keeps its components updated after user interaction, maintaining the interface updated and user-friendly.
"""

# ********RoostGPT********
import pytest
from canvas import Canvas
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from unittest.mock import MagicMock

# Defining the Test Class
class Test_CanvasSetEditing:
    
    # Scenario 1: Test if editing mode is correctly set when value equals True
    @pytest.mark.parametrize('value,expected', [(True, Canvas.EDIT)])
    def test_set_editing_mode_true(self, value, expected):

        # Arrange
        obj_canvas = Canvas()

        # Act
        obj_canvas.set_editing(value)

        # Assert
        assert obj_canvas.mode == expected

    # Scenario 2: Test if creation mode is correctly set when value equals False
    @pytest.mark.parametrize('value,expected', [(False, Canvas.CREATE)])
    def test_set_editing_mode_false(self, value, expected):
        
        # Arrange
        obj_canvas = Canvas()
        obj_canvas.un_highlight = MagicMock()
        obj_canvas.de_select_shape = MagicMock()

        # Act
        obj_canvas.set_editing(value)

        # Assert
        assert obj_canvas.mode == expected
        obj_canvas.un_highlight.assert_called_once()
        obj_canvas.de_select_shape.assert_called_once()

    # Scenario 3: Test if prev_point resets on set_editing invocation
    def test_prev_point_reset_on_set_editing(self):

        # Arrange
        obj_canvas = Canvas()
        obj_canvas.prev_point = QPointF(100,100)

        # Act
        obj_canvas.set_editing()

        # Assert
        assert obj_canvas.prev_point == QPointF()

    # Scenario 4: Check if repaint() is called after set_editing()
    def test_repaint_invocation_on_set_editing(self):

        # Arrange
        obj_canvas = Canvas()
        obj_canvas.repaint = MagicMock()

        # Act
        obj_canvas.set_editing()

        # Assert
        obj_canvas.repaint.assert_called_once()
