# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=write_5b5c9d1d45
ROOST_METHOD_SIG_HASH=write_62b3853644


```
Scenario 1: Verifying Proper Loading of Existing File Data
Details:
  TestName: test_load_existing_file_data
  Description: This test is intended to verify if the function correctly loads data from an existing output file. 
Execution:
  Arrange: Create a dummy output file with known data in the directory that the class instance will reference. Initialize the object with a known set of data.
  Act: Invoke the write method using the object with the known set of data.
  Assert: Check if the data is loaded correctly from the existing output file into the output_dict variable.
Validation:
  This test ensures the proper functioning of the code block designed to load existing data, ensuring that old data is not lost during the function process, endorsing data persistence.

Scenario 2: Handling Non-Existing Output File
Details:
  TestName: test_handle_non_existing_file
  Description: This test is intended to verify whether the function correctly handles the scenario where the output file does not exist.
Execution:
  Arrange: Initialize the object using a filename/path which does not correspond to an existing file.
  Act: Invoke the write method of the object.
  Assert: The output_dict is instantiated as an empty list.
Validation:
  This verifies that the function can handle scenarios were no prior file exists, establishing its robustness to different operating conditions.

Scenario 3: Structuring Output Image Dictionary
Details:
  TestName: test_structure_output_image_dict
  Description: This test is intended to verify whether the function correctly structures the output_image_dict variable with the correct shape annotations.
Execution:
  Arrange: Initialize an object with a known set of shapes data.
  Act: Invoke the write method of the object.
  Assert: The output_image_dict variable contains the correct list of shape annotations as per the shapes data.
Validation:
  This ensures that the shapes input is correctly translated into the output_image_dict, solidifying relevant data transformations.

Scenario 4: Updating of Existing Image Data  
Details:
  TestName: test_update_existing_image_data
  Description: This test is meant to check if the function correctly updates the data of an existing image in the output_dict list.
Execution:
  Arrange: Initialize an object with an existing image's filename and new shape data.
  Act: Invoke the write method of the object.
  Assert: The corresponding image data in the output_dict list is updated with the new shape data.
Validation:
  This confirms the functionality of data updates accurately, protecting the integrity and up-to-dateness of stored information.

Scenario 5: Adding New Image Data
Details:
  TestName: test_add_new_image_data
  Description: This test intends to validate if the function correctly adds new image data to the output_dict when the image does not already exist in the list.
Execution:
  Arrange: Initialize an object with a new image's filename and shape data.
  Act: Invoke the write method of the object.
  Assert: New image data is added to the output_dict list.
Validation:
  This validates the addition of new image data to the output dictionary, maintaining the expansion of stored information.
```
"""

# ********RoostGPT********
import json
from pathlib import Path
from libs.constants import DEFAULT_ENCODING
import os
from create_ml_io import CreateMLWriter
import pytest

@pytest.fixture()
def initial_data():
    return [{
        "image": "existing_image.jpg",
        "verified": False,
        "annotations": [{"label": "existing_shape", "coordinates": { "x": 0.1, "y": 0.1, "width": 0.2, "height": 0.2 }}]
    }]

@pytest.fixture(autouse=True)
def prepare_output_dir(monkeypatch, tmp_path):
    monkeypatch.chdir(tmp_path)

class Test_CreateMlWriterWrite:

    def test_load_existing_file_data(self, initial_data):
        output_file = "test_output.json"
        shapes = [{"label": "shape1", "points": [[0,0],[1,0],[1,1],[0,1]]}]
        Path(output_file).write_text(json.dumps(initial_data), DEFAULT_ENCODING)
        writer = CreateMLWriter("test_folder", "existing_image.jpg", (100,100), shapes, output_file)
        writer.write()
        output_dict = json.loads(Path(output_file).read_text(DEFAULT_ENCODING))
        assert output_dict == initial_data
    
    def test_handle_non_existing_file(self):
        output_file = "non_existing.json"
        shapes = [{"label": "shape1", "points": [[0,0],[1,0],[1,1],[0,1]]}]
        writer = CreateMLWriter("test_folder", "test_image.jpg", (100,100), shapes, output_file)
        writer.write()
        output_dict = json.loads(Path(output_file).read_text(DEFAULT_ENCODING))
        assert output_dict == []
    
    def test_structure_output_image_dict(self):
        output_file = "test_output.json"
        shapes = [{"label": "shape1", "points": [[0,0],[1,0],[1,1],[0,1]]}]
        writer = CreateMLWriter("test_folder", "test_image.jpg", (100,100), shapes, output_file)
        writer.write()
        output_dict = json.loads(Path(output_file).read_text(DEFAULT_ENCODING))
        assert len(output_dict) == 1
        assert output_dict[0]["annotations"][0]["label"] == "shape1"
    
    def test_update_existing_image_data(self, initial_data):
        output_file = "test_output.json"
        shapes = [{"label": "new_shape", "points": [[0,0],[1,0],[1,1],[0,1]]}]
        Path(output_file).write_text(json.dumps(initial_data), DEFAULT_ENCODING)
        writer = CreateMLWriter("test_folder", "existing_image.jpg", (100,100), shapes, output_file)
        writer.write()
        output_dict = json.loads(Path(output_file).read_text(DEFAULT_ENCODING))
        assert output_dict[0]["annotations"][0]["label"] == "new_shape"
    
    def test_add_new_image_data(self, initial_data):
        output_file = "test_output.json"
        shapes = [{"label": "shape1", "points": [[0,0],[1,0],[1,1],[0,1]]}]
        Path(output_file).write_text(json.dumps(initial_data), DEFAULT_ENCODING)
        writer = CreateMLWriter("test_folder", "new_image.jpg", (100,100), shapes, output_file)
        writer.write()
        output_dict = json.loads(Path(output_file).read_text(DEFAULT_ENCODING))
        assert len(output_dict) == 2
        assert output_dict[1]["image"] == "new_image.jpg"
