# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=save_103b3015fa
ROOST_METHOD_SIG_HASH=save_c7c8ce1d88


```
Scenario 1: Valid Case - Saving box data and class list to file when no target file specified
Details:
  TestName: test_save_without_target_file
  Description: This test case verifies that the save function can handle a default scenario when a target file is not provided, and verify whether it correctly writes box data and class list to files.
Execution:
  Arrange: Initialize a valid instance of the class with appropriate parameters. Define a list of boxes in 'box_list' and required 'class_list'.
  Act: Invoke the 'save' method with the class list as a parameter.
  Assert: Check if content of the written files match with the 'box_list' and 'class_list' values given as inputs.
Validation:
  This is a basic functionality of the 'save' method to write the box and class details to a file, which should work correctly when no target file is given. It's important to guarantee the function behaves as expected in standard conditions.

Scenario 2: Valid Case - Saving box data and class list to a target file
Details:
  TestName: test_save_with_target_file
  Description: This test case verifies the behavior of the save function when a target file is provided, to check whether the box data and class list get stored in the target file.
Execution:
  Arrange: Initial setup would be similar to scenario1 with the additional setup of a target file.
  Act: Invoke the 'save' function with the class list and target file as an input.
  Assert: Assert to check if the box data and class list are saved in the target file correctly.
Validation:
  This test verifies the operation of the 'save' method when a target file is provided, which is a critical feature to ensure the save feature's flexibility and usability.

Scenario 3: No box in box_list
Details:
  TestName: test_save_with_no_box_list
  Description: This scenario will test the behavior of the function when the 'box_list' attribute of the object is empty or not provided.
Execution:
  Arrange: Initialize an instance of class without providing any 'box_list' and provide necessary 'class_list'. 
  Act: Call the save function of the instance.
  Assert: Check the content of the files created, to assert that no box related data is written into the files.
Validation:
  Box details are not a mandatory attribute while calling the save function. Hence, it is important to ensure that the function should still execute as expected, writing only class list to the relevant file.

Scenario 4: No class in class_list
Details:
  TestName: test_save_with_no_class_list
  Description: This scenario will test the behavior of the function when the 'class_list' variable provided is empty or not provided.
Execution:
  Arrange: Initialize an instance of the class with necessary parameters along with valid 'box_list' and an empty 'class_list'.
  Act: Call the save function of the instance.
  Assert: Check the content of the files created to assert that no class related data is written into the 'classes.txt'.
Validation:
  Class data is not a mandatory attribute for the save function. Hence, it is significant to ensure that the function executes normally, writing only box details to the target file.
```
"""

# ********RoostGPT********
import os
import codecs
from yolo_io import YOLOWriter
from libs.constants import DEFAULT_ENCODING
import pytest
import tempfile

class Test_YoloWriterSave: 

    def setup(self):
        self.tmpdir = tempfile.TemporaryDirectory()

    def teardown(self):
        self.tmpdir.cleanup()

    @pytest.mark.valid
    def test_save_without_target_file(self):
        writer = YOLOWriter("dir", "name", (100,100))
        writer.box_list = [('class1', (10, 20, 30, 40))]
        class_list = ['class1', 'class2']
        writer.save(class_list)
        with open('name.txt', 'rt') as f:
            assert f.read() == '0 0.250000 0.500000 0.200000 0.200000\n'
        with open('classes.txt', 'rt') as f:
            assert f.read() == 'class1\nclass2\n'

    @pytest.mark.valid
    def test_save_with_target_file(self):
        target_file = os.path.join(self.tmpdir.name, 'target.txt') 
        writer = YOLOWriter("dir", "name", (100,100))
        writer.box_list = [('class1', (10, 20, 30, 40))]
        class_list = ['class1', 'class2']
        writer.save(class_list, target_file)
        with open(target_file, 'rt') as f:
            assert f.read() == '0 0.250000 0.500000 0.200000 0.200000\n'
        with open(os.path.join(self.tmpdir.name, 'classes.txt'), 'rt') as f:
            assert f.read() == 'class1\nclass2\n'

    @pytest.mark.valid
    def test_save_with_no_box_list(self):
        writer = YOLOWriter("dir", "name", (100,100))
        class_list = ['class1', 'class2']
        writer.save(class_list)
        with open('name.txt', 'rt') as f:
            assert f.read() == ''
        with open('classes.txt', 'rt') as f:
            assert f.read() == 'class1\nclass2\n'

    @pytest.mark.valid
    def test_save_with_no_class_list(self):
        target_file = os.path.join(self.tmpdir.name, 'target.txt')
        writer = YOLOWriter("dir", "name", (100,100))
        writer.box_list = [('class1', (10, 20, 30, 40))]
        writer.save([], target_file)
        with open(target_file, 'rt') as f:
            assert f.read() == '-1 0.250000 0.500000 0.200000 0.200000\n'
        with open(os.path.join(self.tmpdir.name, 'classes.txt'), 'rt') as f:
            assert f.read() == ''
