# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=bounded_move_shape_261ac20759
ROOST_METHOD_SIG_HASH=bounded_move_shape_4015033b38


```markdown
Scenario 1: Valid movement within the pixmap
Details:
  TestName: test_valid_movement_within_pixmap
  Description: This test is intended to verify that when a shape is attempted to be moved within the parameters of the pixmap, the function handles the movement correctly and returns True.
Execution:
  Arrange: An instance of the Canvas class, a shape object, and a valid QPointF position within the bounds of the pixmap needs to be initialized.
  Act: Invoke the bounded_move_shape function, passing the shape and the new position.
  Assert: Check that the returned result is True and the shape's new position in the canvas matches the provided one.
Validation:
  This test is important because it validates that the function can correctly process shape movements within the pixmap's boundaries, which is a core functionality of the method.

Scenario 2: Movement outside the pixmap
Details:
  TestName: test_movement_outside_pixmap
  Description: This test is intended to verify that the function correctly handles attempts to move a shape outside the boundaries of the pixmap, preventing such an action and returning False.
Execution:
  Arrange: An instance of the Canvas class, a shape object, and an invalid QPointF position outside the bounds of the pixmap needs to be initialized.
  Act: Invoke the bounded_move_shape function, passing the shape and the new position.
  Assert: Check that the returned result is False and the shape's position in the canvas hasn't changed.
Validation:
  This test is significant because it ensures that the function enforces the requirement that shapes cannot be moved outside of the pixmap's boundaries.

Scenario 3: Movement on the edge of the pixmap
Details:
  TestName: test_movement_on_edge_of_pixmap
  Description: This test is intended to verify that when a shape is attempted to be moved to an edge of the pixmap, the function adjusts the new position to stay within bounds.
Execution:
  Arrange: An instance of the Canvas class, a shape object, and a QPointF position on the edge of the pixmap needs to be initialized.
  Act: Invoke the bounded_move_shape function, passing the shape and the new position.
  Assert: Check that the returned result is True, and the shape's new position on the canvas is adjusted to remain within the pixmap's boundaries.
Validation:
  Enforcing the requirement that shapes should remain within the pixmap's boundaries even when they're moved to or along the edge is critical, and this test confirms that the function correctly implements this behavior.

Scenario 4: No movement
Details:
  TestName: test_no_movement
  Description: This test is intended to verify that the function correctly handles attempts to move a shape to its current position, making no changes and returning False.
Execution:
  Arrange: An instance of the Canvas class is needed along with a shape object and the current position of the shape.
  Act: Invoke the bounded_move_shape function, passing the shape and its current position.
  Assert: Check that the returned result is False and the shape's position on the canvas hasn't changed.
Validation:
  This test is significant because it confirms that unnecessary computations and possible visual flickering are prevented when a no movement action is attempted.
```
"""

# ********RoostGPT********
# Let's start by importing the necessary libraries
import pytest
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *

from libs.shape import Shape
from canvas import Canvas

# Define a common setup function to avoid code repetition
@pytest.fixture
def setup_canvas_and_shape():
    canvas = Canvas()
    shape = Shape(points=[QPoint(10, 10), QPoint(20, 20)])
    # setting prev_point for canvas
    canvas.prev_point = QPointF(10, 10)
    return canvas, shape

@pytest.mark.regression
@pytest.mark.valid
def test_valid_movement_within_pixmap(setup_canvas_and_shape):
    canvas, shape = setup_canvas_and_shape
    new_position = QPointF(30, 30)
    
    result = canvas.bounded_move_shape(shape, new_position)

    assert result is True
    assert shape.points[0] == QPointF(30, 30)
    assert shape.points[1] == QPointF(40, 40)


@pytest.mark.regression
@pytest.mark.invalid
def test_movement_outside_pixmap(setup_canvas_and_shape):
    canvas, shape = setup_canvas_and_shape
    new_position = QPointF(-10, -10)  # position outside the pixmap

    result = canvas.bounded_move_shape(shape, new_position)

    assert result is False
    assert shape.points[0] == QPointF(10, 10)
    assert shape.points[1] == QPointF(20, 20)


@pytest.mark.regression
@pytest.mark.valid
def test_movement_on_edge_of_pixmap(setup_canvas_and_shape):
    canvas, shape = setup_canvas_and_shape
    new_position = QPointF(canvas.pixmap.width(), canvas.pixmap.height())  # position at the edge of pixmap
    
    result = canvas.bounded_move_shape(shape, new_position)

    assert result is True
    assert shape.points[0] == QPointF(canvas.pixmap.width() - 10, canvas.pixmap.height() - 10)
    assert shape.points[1] == QPointF(canvas.pixmap.width(), canvas.pixmap.height())


@pytest.mark.regression
@pytest.mark.no_movement
def test_no_movement(setup_canvas_and_shape):
    canvas, shape = setup_canvas_and_shape
    current_position = QPointF(10, 10)

    result = canvas.bounded_move_shape(shape, current_position)

    assert result is False
    assert shape.points[0] == QPointF(10, 10)
    assert shape.points[1] == QPointF(20, 20)
