# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=mouseDoubleClickEvent_9846b4a034
ROOST_METHOD_SIG_HASH=mouseDoubleClickEvent_bc7633a483


Scenario 1: Test double click event with non-closable polygon
Details:
  TestName: test_mouse_double_click_event_cannot_close_shape
  Description: This test verifies the behavior of the function when the polygon drawn is not closable. This happens when the current shape cannot be closed or does not have greater than 3 points.
Execution:
  Arrange: Create a Canvas instance and initialize a Shape instance with fewer than 4 points in the 'current' attribute and set 'can_close_shape()' to return False.
  Act: Call the 'mouseDoubleClickEvent' function with an arbitrary event.
  Assert: Assert that the function does not modify the 'current' Shape instance since it cannot be closed.
Validation:
  This test is important as it ensures that the method properly handles cases where the drawn shape is not ready to be closed, preventing unwanted modifications to the non-completable shape and possible exceptions.

Scenario 2: Test double click event with closable polygon
Details:
  TestName: test_mouse_double_click_event_can_close_shape
  Description: This test verifies the function when the polygon drawn is ready to be closed, i.e., it satisfies the conditions of 'can_close_shape()' and has a length greater than 3.
Execution:
  Arrange: Create a Canvas instance and initialize a Shape instance with more than 3 points in the 'current' attribute and set 'can_close_shape()' to return True.
  Act: Call the 'mouseDoubleClickEvent' function with an arbitrary event.
  Assert: Assert that the 'current' Shape instance is finalised. This signifies that the 'current' attribute becomes None and the shape is appended to the 'shapes' attribute.
Validation:
  This test scenario is crucial for validating that the function correctly finalises valid polygons. It ensures that the drawing tool operates correctly, finalising and storing the completed shape when the user signals its completion via a double click.

Scenario 3: Test double click event with exactly 4 points
Details:
  TestName: test_mouse_double_click_event_exact_four_points
  Description: This test verifies the function when the shape has exactly 4 points. The fourth point, created by a single click before the double-click event, should be popped before the shape is finalised.
Execution:
  Arrange: Create a Canvas instance and initialize a Shape instance with exactly 4 points in the 'current' attribute. Ensure 'can_close_shape()' returns True.
  Act: Call the 'mouseDoubleClickEvent' function with an arbitrary event.
  Assert: Assert that the popped point is not part of the final shape and that the final shape has 3 points.
Validation:
  This scenario is important to ensure that the extra point generated by the single click part of the double-click event is correctly removed before finalising the shape. It confirms the need to account for double-click behavior in the tool's drawing process.
"""

# ********RoostGPT********
import pytest
from PyQt5.QtGui import *
from canvas import Canvas
from libs.shape import Shape

class Test_CanvasMouseDoubleClickEvent:

    def test_mouse_double_click_event_cannot_close_shape(self, mocker):
        # Arrange
        mocker.patch.object(Shape, 'can_close_shape', return_value=False)
        canvas = Canvas()
        canvas.current = Shape()
        canvas.current.add_point(QPointF(0, 0))
        canvas.current.add_point(QPointF(1, 1))
        
        # Act
        canvas.mouseDoubleClickEvent(QMouseEvent(QEvent.MouseButtonDblClick, QPointF(), Qt.NoButton, Qt.NoButton, Qt.NoModifier))

        # Assert
        assert len(canvas.current) == 2
        assert canvas.shapes == []

    def test_mouse_double_click_event_can_close_shape(self, mocker):
        # Arrange
        mocker.patch.object(Shape, 'can_close_shape', return_value=True)
        canvas = Canvas()
        canvas.current = Shape()
        for _ in range(4):
            canvas.current.add_point(QPointF())
        
        # Act
        canvas.mouseDoubleClickEvent(QMouseEvent(QEvent.MouseButtonDblClick, QPointF(), Qt.NoButton, Qt.NoButton, Qt.NoModifier))

        # Assert
        assert canvas.current is None
        assert len(canvas.shapes) == 1

    def test_mouse_double_click_event_exact_four_points(self, mocker):
        # Arrange
        mocker.patch.object(Shape, 'can_close_shape', return_value=True)
        canvas = Canvas()
        canvas.current = Shape()
        for i in range(4):
            canvas.current.add_point(QPointF(i,i))

        previous_point = canvas.current[-1]
        
        # Act
        canvas.mouseDoubleClickEvent(QMouseEvent(QEvent.MouseButtonDblClick, QPointF(), Qt.NoButton, Qt.NoButton, Qt.NoModifier))

        # Assert
        assert previous_point not in canvas.shapes[0]
        assert len(canvas.shapes[0]) == 3
