# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=handle_drawing_6c8508d120
ROOST_METHOD_SIG_HASH=handle_drawing_d3305a8c26


Scenario 1: Testing whether the maximal points limit of the current shape is validated
Details:
  TestName: test_max_points_limit
  Description: This test verifies that the method handle_drawing correctly identifies when the current shape reaches its maximum allowed points and prevents further points from being added.
Execution:
  Arrange: Initialize a Shape object with the maximum allowed points and assign it to self.current.
  Act: Invoke handle_drawing with a valid position.
  Assert: Verify that the method does not attempt to add more points to the Shape object.
Validation:
  This test is necessary to ensure that the system enforces the business rules about the maximum allowed points per shape.

Scenario 2: Validation of point addition when shape has not reached the maximum points
Details:
  TestName: test_point_addition_when_below_max
  Description: This test verifies that when the current shape has not reached the maximum points, the method correctly adds points to the shape.
Execution:
  Arrange: Initialize a Shape object with less than the maximum allowed points and assign it to self.current.
  Act: Invoke handle_drawing with a valid position.
  Assert: Verify that the new point is added to the Shape object.
Validation:
  This test ensures handle_drawing can correctly add points to a shape under normal operational circumstances.

Scenario 3: Testing the end of the drawing process when shape has reached maximum points
Details:
  TestName: test_drawing_end_when_reached_max_points
  Description: This test checks whether the drawing is finalized when the shape being drawn has reached the maximum points.
Execution:
  Arrange: Initialize a Shape object with the maximum allowed points and assign it to self.current.
  Act: Invoke handle_drawing.
  Assert: Verify the call of the finalise function and the emission of the drawPolygon signal with a False parameter.
Validation:
  This test ensures the code correctly finalizes the drawing when a shape has reached the maximum points.

Scenario 4: Testing the initiation of a new shape
Details:
  TestName: test_initiation_new_shape
  Description: This test checks whether the handle_drawing method correctly starts the drawing of a new shape when the given position is not out of pixmap and there are no active shapes being drawn.
Execution:
  Arrange: Ensure self.current is None and the provided position is within pixmap boundaries.
  Act: Invoke handle_drawing with a valid position.
  Assert: Verify that a new Shape object is created, the given position is added as a point to shape, and the drawPolygon signal is emitted with a True parameter.
Validation:
  This test is crucial to validate the start of a new shape drawing process under valid conditions.

Scenario 5: Testing behavior for out of pixmap position
Details:
  TestName: test_out_of_pixmap_position
  Description: This test verifies that handle_drawing does not create a new shape or add points to existing shapes when called with an out-of-pixmap position.
Execution:
  Arrange: Ensure the provided position is out of pixmap.
  Act: Invoke handle_drawing with an out-of-pixmap position.
  Assert: Verify that no new Shape object is created and no points are added to existing shapes.
Validation:
  This test validates that the code does not attempt to draw where it should not, acting as a boundary guard against out-of-pixmap drawings.
"""

# ********RoostGPT********
import pytest
from PyQt5.QtCore import QPointF
from unittest.mock import MagicMock
from canvas import Canvas
from libs.shape import Shape


class Test_CanvasHandleDrawing:
    @pytest.mark.parametrize("max_points_reached", [True, False])
    def test_max_points_limit(self, max_points_reached):
        canvas = Canvas()
        canvas.finalise = MagicMock()
        canvas.current = Shape()
        point = QPointF(2, 2)
        canvas.current.add_point(point)
        canvas.current.add_point(point)
        canvas.current.reach_max_points = MagicMock(return_value=max_points_reached)
        
        canvas.handle_drawing(point)
        if max_points_reached:
            assert len(canvas.current.points) == 2
        else:
            assert len(canvas.current.points) == 2
            
    def test_point_addition_when_below_max(self):
        canvas = Canvas()
        canvas.finalise = MagicMock()
        canvas.current = Shape()
        point = QPointF(2, 2)
        canvas.current.add_point(point)
        
        canvas.handle_drawing(point)
        assert len(canvas.current.points) == 2
        
    def test_drawing_end_when_reached_max_points(self):
        canvas = Canvas()
        canvas.finalise = MagicMock()
        canvas.current = Shape()
        point = QPointF(2, 2)
        for _ in range(4):
            canvas.current.add_point(point)
        
        canvas.handle_drawing(point)
        assert canvas.finalise.called
        
    def test_initiation_new_shape(self):
        canvas = Canvas()
        canvas.finalise = MagicMock()
        canvas.current = None
        point = QPointF(2, 2)
        
        canvas.handle_drawing(point)
        assert isinstance(canvas.current, Shape)
        assert len(canvas.current.points) == 1

        
    def test_out_of_pixmap_position(self):
        canvas = Canvas()
        canvas.finalise = MagicMock()
        canvas.current = Shape()
        point = QPointF(2, 2)
        canvas.out_of_pixmap = MagicMock(return_value=True)
        
        canvas.handle_drawing(point)
        assert len(canvas.current.points) == 0
