# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=__init___b280e02d7b
ROOST_METHOD_SIG_HASH=__init___38bba464f8


```
Scenario 1: Testing the initialization with minimum required parameters 
Details:
  TestName: test_min_required_params_init
  Description: The test is intended to verify that the function initialize correctly with only folder_name, filename and img_size parameters. The initialization assumes default values for unspecified parameters.
Execution:
  Arrange: No specific setup is required for this test case.
  Act: Invoke the function __init__ with the parameters folder_name='folder', filename='imagefile', and img_size=(128, 128).
  Assert: Check whether the object's properties match the values provided and unspecified parameters have their default values.
Validation:
  This test ensures that the function is able to handle minimum required parameters and is assigning default values properly for unspecified parameters.

Scenario 2: Testing the initialization with all parameters specified 
Details:
  TestName: test_all_params_init
  Description: The test is intended to verify that the function initializes correctly with all parameters defined, including the database_src and local_img_path.
Execution:
  Arrange: No specific setup is required for this test case.
  Act: Invoke the function __init__ with parameter values folder_name='folder', filename='imagefile', img_size=(128, 128), database_src='db1' and local_img_path='path/to/image'.
  Assert: Check whether the properties of the object match the values provided, and unspecified fields have their default values.
Validation:
  This test ensures that the function works correctly when all parameters are provided.

Scenario 3: Testing the default property values after initialization
Details:
  TestName: test_default_property_values
  Description: The test is intended to verify that the function initializes with its box_list property as an empty array and verified property as False.
Execution:
  Arrange: No specific setup is required for this test case.
  Act: Invoke the function __init__ with any set of parameters.
  Assert: Check that the box_list property is an empty array and the verified property is false.
Validation:
  This test ensures that properties box_list and verified are properly defaulted during initialization.

Scenario 4: Testing the initialization with invalid img_size inputs
Details:
  TestName: test_invalid_img_size
  Description: The test is intended to verify that the function handles invalid img_size inputs, for example non-tuple values or tuples of length other than 2.
Execution:
  Arrange: No specific setup is required for this test case.
  Act: Invoke the function __init__ with img_size parameter as some invalid value such as int, or tuple of length less than or more than 2.
  Assert: The function should raise an appropriate exception.
Validation:
  Even though Python is dynamically typed, this test ensures that function deals correctly with inappropriate data types for img_size which is expected to be a tuple.
```

"""

# ********RoostGPT********
import pytest
import codecs
import os
from libs.constants import DEFAULT_ENCODING
from yolo_io import YOLOWriter

class Test_YoloWriterInit:
    
    def test_min_required_params_init(self):
        yolo_writer = YOLOWriter('folder', 'imagefile', (128, 128))
        assert yolo_writer.folder_name == 'folder'
        assert yolo_writer.filename == 'imagefile'
        assert yolo_writer.img_size == (128, 128)
        assert yolo_writer.database_src == 'Unknown'
        assert yolo_writer.local_img_path is None
        assert yolo_writer.box_list == []
        assert yolo_writer.verified == False

    def test_all_params_init(self):
        yolo_writer = YOLOWriter('folder', 'imagefile', (128, 128), 'db1', 'path/to/image')
        assert yolo_writer.folder_name == 'folder'
        assert yolo_writer.filename == 'imagefile'
        assert yolo_writer.img_size == (128, 128)
        assert yolo_writer.database_src == 'db1'
        assert yolo_writer.local_img_path == 'path/to/image'
        assert yolo_writer.box_list == []
        assert yolo_writer.verified == False

    def test_default_property_values(self):
        yolo_writer = YOLOWriter('folder', 'imagefile', (128, 128))
        assert yolo_writer.box_list == []
        assert yolo_writer.verified == False

    def test_invalid_img_size(self):
        with pytest.raises(Exception):
            YOLOWriter('folder', 'imagefile', 128)
        with pytest.raises(Exception):
            YOLOWriter('folder', 'imagefile', (128,))
        with pytest.raises(Exception):
            YOLOWriter('folder', 'imagefile', (128, 128, 128))
