# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=bounded_move_vertex_abaedbad65
ROOST_METHOD_SIG_HASH=bounded_move_vertex_356ca00b3f


```
Scenario 1: Testing "bounded_move_vertex" function with valid position inside pixmap
Details:
  TestName: test_bounded_move_vertex_inside_pixmap
  Description: This test is intended to verify if the "bounded_move_vertex" function moves the vertex correctly when the given position is within the pixmap.
Execution:
  Arrange: Initialize a canvas object, a shape object, and a position inside the pixmap.
  Act: Invoke bounded_move_vertex() function has to be invoked with the position inside the pixmap.
  Assert: Verify that the vertex of shape is correctly moved according to the specified rules, and the shape's points have been shifted as expected.
Validation:
  This test is important to confirm that the vertices of shapes can be moved correctly when given valid positions, ensuring the integrity of drawn shapes in the canvas.

Scenario 2: Testing "bounded_move_vertex" function with position out of pixmap
Details:
  TestName: test_bounded_move_vertex_outside_pixmap
  Description: This test is intended to verify if the "bounded_move_vertex" function correctly clips the position and then moves the vertex when the provided position is outside the pixmap.
Execution:
  Arrange: Initialize a canvas object, a shape object, and a position outside the pixmap.
  Act: Invoke "bounded_move_vertex" function with the position outside the pixmap.
  Assert: Check that the position is correctly clipped and then verify that the vertex is moved accurately, and the shape's points have been shifted as expected.
Validation:
  This test is crucial to ensure that any positional inputs given outside the pixmap boundary are handled properly, maintaining the accuracy of shapes' position within the canvas.

Scenario 3: Testing "bounded_move_vertex" function, when 'draw_square' is True
Details:
  TestName: test_bounded_move_vertex_draw_square_True
  Description: This test verifies how the "bounded_move_vertex" function behaves with 'draw_square' flag set to True. It checks how the function handles the shifting of vertices in this scenario.
Execution:
  Arrange: Initialize a canvas object, set 'draw_square' as True, a shape object, and a position.
  Act: Invoke "bounded_move_vertex" function with the position.
  Assert: Verify that the vertex of shape is correctly moved and the points of the shape have been shifted correctly considering all square drawing conditions.
Validation:
  This test is significant to confirm that when 'draw_square' flag is set to True, the vertices of shapes are handled and shifted correctly, maintaining the consistency of shape properties.

Scenario 4: Testing "bounded_move_vertex" function under specific indexes causing unique vertex movement
Details:
  TestName: test_bounded_move_vertex_special_indexes
  Description: This test is intended to verify whether the "bounded_move_vertex" function correctly handles some specific indexes which can result in unique vertex moves.
Execution:
  Arrange: Initialize a canvas object, a shape object and positions causing specific index scenario.
  Act: Invoke "bounded_move_vertex" with positions causing specific index scenario.
  Assert: Check that the vertices of shape are moved accurately and as per the special rules related to specific index.
Validation:
  This test ensures that the function performs as expected under diverse input conditions, preserving faithful index-based vertex management.
```

"""

# ********RoostGPT********
import pytest
from canvas import Canvas
from PyQt5.QtGui import QPixmap, QPointF
from libs.shape import Shape

@pytest.mark.regression
def test_bounded_move_vertex_inside_pixmap():
    canvas = Canvas()
    shape = Shape()
    canvas.shapes.append(shape)
    shape.points = [QPointF(10, 10), QPointF(20, 10), QPointF(20, 20), QPointF(10, 20)]
    canvas.pixmap = QPixmap(500, 500)
    move_pos = QPointF(50, 50)

    canvas.h_vertex = 1
    canvas.h_shape = shape
    canvas.bounded_move_vertex(move_pos)
    expected_points = [QPointF(10, 10), QPointF(50, 10), QPointF(50, 50), QPointF(10, 50)]
    assert shape.points == expected_points

@pytest.mark.regression
def test_bounded_move_vertex_outside_pixmap():
    canvas = Canvas()
    shape = Shape()
    canvas.shapes.append(shape)
    shape.points = [QPointF(10, 10), QPointF(20, 10), QPointF(20, 20), QPointF(10, 20)]
    canvas.pixmap = QPixmap(50, 50)
    move_pos = QPointF(70, 70)

    canvas.h_vertex = 1
    canvas.h_shape = shape
    canvas.bounded_move_vertex(move_pos)
    expected_points = [QPointF(10, 10), QPointF(30, 10), QPointF(30, 30), QPointF(10, 30)]
    assert shape.points == expected_points

@pytest.mark.regression
def test_bounded_move_vertex_draw_square_True():
    canvas = Canvas()
    shape = Shape()
    canvas.shapes.append(shape)
    shape.points = [QPointF(10, 10), QPointF(20, 10), QPointF(20, 20), QPointF(10, 20)]
    canvas.pixmap = QPixmap(500, 500)
    canvas.draw_square = True
    move_pos = QPointF(60, 60)

    canvas.h_vertex = 1
    canvas.h_shape = shape
    canvas.bounded_move_vertex(move_pos)
    expected_points = [QPointF(10, 10), QPointF(60, 10), QPointF(60, 60), QPointF(10, 60)]
    assert shape.points == expected_points

@pytest.mark.regression
def test_bounded_move_vertex_special_indexes():
    canvas = Canvas()
    shape = Shape()
    canvas.shapes.append(shape)
    shape.points = [QPointF(10, 10), QPointF(20, 10), QPointF(20, 20), QPointF(10, 20)]
    canvas.pixmap = QPixmap(500, 500)

    canvas.h_vertex = 0
    canvas.h_shape = shape
    canvas.bounded_move_vertex(QPointF(50, 50))
    expected_points = [QPointF(50, 50), QPointF(60, 50), QPointF(60, 60), QPointF(50, 60)]
    assert shape.points == expected_points
