# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=mouseMoveEvent_2254ea6b34
ROOST_METHOD_SIG_HASH=mouseMoveEvent_7e8316c531


Scenario 1: Test drawing mode with drawing a Polygon inside an image.
Details:
  TestName: test_draw_polygon_in_image
  Description: This test is designed to simulate a typical use case where the mouse is used to draw a polygon on the image. It tests whether a new polygon is correctly created and drawn while in the drawing mode.
Execution:
  Arrange: Instantiate a Canvas object, and set the mode to drawing (self.mode = self.CREATE).
  Act: Invoke mouseMoveEvent method with an event object possessing an 'in-image' positional attribute, mimicking the actions of drawing a polygon.
  Assert: The 'drawing_line_color' of the member 'current' should be equal to the drawing color. Also, ensure a canvas has been updated or refreshed by checking the last call to self.repaint().
Validation:
  This test ensures the user can draw a polygon when in a drawing mode and each mouse movement should reflect a change in graphic context, ensuring real-time drawing.

Scenario 2: Move Vertex of a Selected Polygon
Details:
  TestName: test_move_vertex_of_selected_polygon
  Description: This test is purposed to simulate the case where the user is moving a single vertex of a selected polygon using mouse interactions.
Execution:
  Arrange: Instantiate a Canvas object and set a selected shape and h_vertex to mimic having a selected polygon with a selected vertex.
  Act: Call the mouseMoveEvent method with an event object encapsulating a new positional attribute representing the new location of the vertex.
  Assert: Check if the position of the selected vertex of the selected shape has correctly updated to the new location.
Validation:
  The importance of this test is to validate that a user can move a single vertex of a selected polygon.

Scenario 3: Test Move Entire Selected Shape Within the Image
Details:
  TestName: test_move_entire_selected_shape
  Description: This test is for the scenario where a user wants to move an entire shape by clicking and dragging it to a new location using mouse interactions.
Execution:
  Arrange: Create a Canvas object with a 'self.selected_shape' as a polygon inside the canvas.
  Act: Call the mouseMoveEvent method with an event object having a defined positional attribute corresponding to the new location of the shape.
  Assert: The position of the polygon ('self.selected_shape') should be updated to the new position.
Validation:
  This test confirms that users can smoothly move a shape on the canvas and immediately preview its new position.

Scenario 4: Test Hover Over Shape and Vertex
Details:
  TestName: test_hover_over_shape_and_vertex
  Description: This test handles the case where the mouse hovers over a shape or a vertex but no button is clicked to interact with them.
Execution:
  Arrange: Instantiate a Canvas object with a shape over which the mouse will be hovered.
  Act: Invoke mouseMoveEvent with an event object with positional attributes corresponding to the positional attributes of the shape or vertex.
  Assert: Check if the cursor changes to CURSOR_POINT when hovering over the vertex, to CURSOR_GRAB when hovering over the shape, and to CURSOR_DEFAULT when not hovering over anything. Also, validate if the tooltip changes properly.
Validation:
  This test is important because it ensures the user has a clear indication of the object their cursor is hovering over, which promotes better interaction with the application.  

Scenario 5: Test Pan Inside an Image
Details:
  TestName: test_pan_in_image
  Description: It tests the pan condition when the user has not selected a shape or vertex and moves the mouse while clicking the left button for panning.
Execution:
  Arrange: Instantiate a Canvas object with the desired image.
  Act: Call the mouseMoveEvent method with event objects having positional attributes reflecting a mouse move with the left button pressed.
  Assert: Check if the canvas emits scrollRequest properly based on the delta of the mouse moment.
Validation:
  This test is required to validate the panning feature, greatly impacting user experience while navigating larger images.
"""

# ********RoostGPT********
import pytest
from PyQt5.QtGui import QColor, QPixmap, QPainter, QMouseEvent
from PyQt5.QtCore import QPointF, Qt
from PyQt5.QtWidgets import QMenu, QApplication

from shapes.shape import Shape
from canvas import Canvas
from libs.constants import *
from unittest.mock import MagicMock

class Test_CanvasMouseMoveEvent:

    @pytest.mark.parametrize("start,end", [
        (QPointF(10, 10), QPointF(20, 20)),
    ])
    def test_draw_polygon_in_image(self, start, end):
        canvas = Canvas()
        canvas.mode = canvas.CREATE
        canvas.pixmap = QPixmap(100, 100)
        canvas.current = Shape()
        canvas.repaint = MagicMock()

        event = QMouseEvent(QEvent.MouseMove, end, Qt.NoButton, Qt.NoButton, Qt.NoModifier)
        canvas.mouseMoveEvent(event)

        assert canvas.current.drawing_line_color == canvas.drawing_line_color
        assert canvas.repaint.called

    @pytest.mark.parametrize("old_pos,new_pos", [
        (QPointF(50, 50), QPointF(60, 60)),
    ])
    def test_move_vertex_of_selected_polygon(self, old_pos, new_pos):
        canvas = Canvas()
        canvas.h_vertex = 0
        canvas.h_shape = Shape([old_pos, old_pos, old_pos])
        event = QMouseEvent(QEvent.MouseMove, new_pos, Qt.NoButton, Qt.NoButton, Qt.NoModifier)

        canvas.mouseMoveEvent(event)

        assert canvas.h_shape[0] == new_pos

    def test_move_entire_selected_shape(self):
        old_pos = QPointF(50, 50)
        new_pos = QPointF(60, 60)
        shape = Shape([old_pos, old_pos, old_pos])
        canvas = Canvas()
        canvas.selected_shape = shape
        
        event = QMouseEvent(QEvent.MouseMove, new_pos, Qt.NoButton, Qt.NoButton, Qt.NoModifier)

        canvas.mouseMoveEvent(event)

        assert canvas.selected_shape[0] == new_pos

    def test_hover_over_shape_and_vertex(self):
        pos = QPointF(50, 50)
        canvas = Canvas()
        shape = Shape([pos, pos, pos])
        shape.fill = True
        shape.label="Test Shape"
        canvas.shapes.append(shape)

        event = QMouseEvent(QEvent.MouseMove, pos, Qt.NoButton, Qt.NoButton, Qt.NoModifier)

        canvas.mouseMoveEvent(event)

        assert QApplication.overrideCursor() == CURSOR_GRAB
        assert canvas.toolTip() == "Click & drag to move shape '%s'" % shape.label

    def test_pan_in_image(self):
        old_pos = QPointF(50, 50)
        new_pos = QPointF(60, 60)

        canvas = Canvas()
        canvas.pixmap = QPixmap(100, 100)
        canvas.scrollRequest = MagicMock()
        canvas.update = MagicMock()

        press_event = QMouseEvent(QEvent.MouseButtonPress, old_pos, Qt.LeftButton, Qt.LeftButton, Qt.NoModifier)
        move_event = QMouseEvent(QEvent.MouseMove, new_pos, Qt.LeftButton, Qt.LeftButton, Qt.NoModifier)

        canvas.mouseMoveEvent(press_event)
        canvas.mouseMoveEvent(move_event)

        assert canvas.scrollRequest.emit.called
        assert canvas.update.called
