# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=append_objects_3866a35fdc
ROOST_METHOD_SIG_HASH=append_objects_84ea6dfd14


Scenario 1: Testing append_objects when each object is not truncated and the name conversion
Details:
  TestName: test_append_objects_without_truncated
  Description: This test is intended to verify that append_objects correctly appends the objects into 'top' and handles the conversion of 'name' to ustr correctly. It also checks whether objects are not truncated and that associated flags are correctly set.
Execution:
  Arrange: Needs inputs as folder_name, filename, img_size, database_src, local_img_path for the constructors. Create an instance of the class and add some objects in the box_list where none of the objects are trunceted.
  Act: Call the function append_objects and pass 'top' xml element.
  Assert: Check whether all the objects are correctly represented in the 'top' xml element with the name being converted to ustr, and truncated flag being set as "0".
Validation:
  This test is vital as it verifies the basic functionality of append_objects method when objects are not truncated. It ensures the objects are correctly appended and tags are set properly in the xml document.

Scenario 2: Testing append_objects when objects are truncated vertically
Details:
  TestName: test_append_objects_with_vertical_truncation
  Description: This test is intended to verify that append_objects sets the 'truncated' flag correctly when objects are truncated vertically i.e., ymax equals image height or ymin equals 1.
Execution:
  Arrange: Requires inputs as folder_name, filename, img_size, database_src, local_img_path for the constructors. Create an instance of the class and add some objects in the box_list where ymax equals to image height or ymin equals to 1.
  Act: Call the function append_objects and pass 'top' xml element.
  Assert: Check the 'truncated' flag of the objects in the 'top' element to be "1".
Validation:
  This test is very important from a data cleaning point of view as it ensures that all the vertically truncated objects are correctly represented in the xml document.

Scenario 3: Testing append_objects when objects are truncated horizontally
Details:
  TestName: test_append_objects_with_horizontal_truncation
  Description: This test is intended to verify that the append_objects function sets the 'truncated' flag appropriatly when the objects are truncated horizontally i.e., xmax equals to image width or xmin equals 1
Execution:
  Arrange: Needs inputs as folder_name, filename, img_size, database_src, local_img_path for the constructors. Create an instance of the class and add some objects in the box_list where xmax equals to image width or xmin equals to 1.
  Act: Call the function append_objects and pass 'top' xml element.
  Assert: Check the 'truncated' flag of the objects in the 'top' element to be "1".
Validation:
  This test is essential to ensure correct data processing as it checks that all the horizontally truncated objects are correctly marked in the xml document. 

Scenario 4: Testing difficult objects
Details:
  TestName: test_append_objects_with_difficult_objects
  Description: This test is intended to verify that append_objects handles 'difficult' object flag correctly.
Execution:
  Arrange: Requires inputs as folder_name, filename, img_size, database_src, local_img_path for the constructors. Create an instance of the class and add some objects in the box_list with 'difficult' flag set.
  Act: Call function append_objects and pass 'top' xml element.
  Assert: Test if the 'difficult' flag of the objects in the 'top' element is consistent with the input objects.
Validation:
  This test is critical for correct object classification as it ensures that all the 'difficult' objects are correctly labelled in the xml document.
"""

# ********RoostGPT********
import sys
from xml.etree import ElementTree
from xml.etree.ElementTree import Element, SubElement
from lxml import etree
import codecs
import pytest
from libs.constants import DEFAULT_ENCODING
from libs.ustr import ustr
from pascal_voc_io import PascalVocWriter

class Test_PascalVocWriterAppendObjects(object):

    @pytest.mark.regression
    def test_append_objects_without_truncated(self):
        writer = PascalVocWriter('folder', 'file', (image_height, image_width), 'Unknown', 'path')
        box = {'name': 'obj', 'xmin': 10, 'ymin': 10, 'xmax': 50, 'ymax': 50, 'difficult': False}
        writer.box_list.append(box)
        top = Element('annotation')
        writer.append_objects(top)
        assert top.find("object/truncated").text == "0"
        assert top.find("object/name").text == box['name']

    @pytest.mark.regression
    def test_append_objects_with_vertical_truncation(self):
        writer = PascalVocWriter('folder', 'file', (image_height, image_width), 'Unknown', 'path')
        box = {'name': 'obj', 'xmin': 10, 'ymin': 1, 'xmax': 50, 'ymax': image_height, 'difficult': False}
        writer.box_list.append(box)
        top = Element('annotation')
        writer.append_objects(top)
        assert top.find("object/truncated").text == "1"

    @pytest.mark.regression
    def test_append_objects_with_horizontal_truncation(self):
        writer = PascalVocWriter('folder', 'file', (image_height, image_width), 'Unknown', 'path')
        box = {'name': 'obj', 'xmin': 1, 'ymin': 10, 'xmax': image_width, 'ymax': 50, 'difficult': False}
        writer.box_list.append(box)
        top = Element('annotation')
        writer.append_objects(top)
        assert top.find("object/truncated").text == "1"

    @pytest.mark.regression
    def test_append_objects_with_difficult_objects(self):
        writer = PascalVocWriter('folder', 'file', (image_height, image_width), 'Unknown', 'path')
        box = {'name': 'obj', 'xmin': 10, 'ymin': 20, 'xmax': 50, 'ymax': 50, 'difficult': True}
        writer.box_list.append(box)
        top = Element('annotation')
        writer.append_objects(top)
        assert top.find("object/difficult").text == "1"
