# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=mousePressEvent_ced9e53373
ROOST_METHOD_SIG_HASH=mousePressEvent_1a55af5f66


```
Scenario 1: Test for left mouse click in drawing mode
Details:
  TestName: test_mousePressEvent_drawing_left_click
  Description: This test verifies if the transform and handle_drawing methods are called when the left key of the mouse is pressed in the drawing mode.
Execution:
  Arrange: Mock 'self.transform_pos', 'self.drawing', and 'self.handle_drawing' functions. Also, construct a mock QMouse event with the left button pressed.
  Act: Call mousePressEvent with the mock event.
  Assert: Validate if transform_pos and handle_drawing functions are called.
Validation:
  The test verifies that when the user gives input through the left mouse button while in the drawing mode, the point is transformed and it correctly transitions to the handling of drawing.

Scenario 2: Test for left mouse click in editing mode
Details:
  TestName: test_mousePressEvent_editing_left_click
  Description: This test validates the selection and panning function when the left key of the mouse is pressed in the editing mode.
Execution:
  Arrange: Mock 'transform_pos', 'editing', 'drawing', 'select_shape_point' and panning functions. Construct a mock QMouse event with the left button pressed.
  Act: Call mousePressEvent with the mock event.
  Assert: Validate if the 'select_shape_point' and the panning functions are called.
Validation:
  The test ensures that when the user gives input via the left mouse button in the editing mode, the selection and panning process executes properly, reflecting user's interactions.

Scenario 3: Test for right mouse click in editing mode
Details:
  TestName: test_mousePressEvent_editing_right_click
  Description: This test checks if the 'select_shape_point' method is executed when the right button is pressed in the editing mode.
Execution:
  Arrange: Mock 'transform_pos', 'editing', 'select_shape_point' functions. Construct a mock QMouse event with the right button pressed.
  Act: call mousePressEvent with the mock event.
  Assert: Validate if the 'select_shape_point' method is called.
Validation:
  The test confirms the correct execution of the selection process, making sure that the shape selection through right-click is working correctly in the editing mode.

Scenario 4: Test for functionality in invalid mode or invalid mouse input
Details:
  TestName: test_mousePressEvent_invalid_mode_or_mouse_input
  Description: This test makes sure that none of the functions ('handle_drawing' or 'select_shape_point') are called when the input is invalid.
Execution:
  Arrange: Mock 'transform_pos', 'editing', 'drawing', 'select_shape_point', 'handle_drawing' functions. Construct a mock QMouse event with the middle/right button (in drawing mode) or middle button (in editing mode) pressed.
  Act: Call mousePressEvent with the mock event.
  Assert: Validate that none of the 'select_shape_point' or 'handle_drawing' functions are called.
Validation:
  The test verifies proper error handling for invalid input and ensures that code behaves expectedly not executing any unrelated functions.
```
"""

# ********RoostGPT********
import pytest
from unittest.mock import MagicMock, patch
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from libs.shape import Shape

from canvas import Canvas

@pytest.mark.parametrize("button,module", [(Qt.LeftButton, 'Canvas.drawing'), (Qt.RightButton, 'Canvas.editing')], ids=['drawing', 'editing'])
class Test_CanvasMousePressEvent:

    def test_mousePressEvent_drawing_left_click(self, qapp, button, module):
        with patch('Canvas.transform_pos'), patch('Canvas.handle_drawing'), patch(module, return_value=True):
            canvas = Canvas()
            mock_event = MagicMock()
            mock_event.button.return_value = button
            canvas.mousePressEvent(mock_event)
            canvas.transform_pos.assert_called_once_with(mock_event.pos())
            canvas.handle_drawing.assert_called_once_with(canvas.transform_pos.return_value)

    def test_mousePressEvent_editing_left_click(self, qapp, button, module):
        with patch('Canvas.transform_pos'), patch('Canvas.select_shape_point'), patch(module, return_value=True):
            canvas = Canvas()
            mock_event = MagicMock()
            mock_event.button.return_value = button
            mock_event.pos.return_value = "some_event_position"
            canvas.mousePressEvent(mock_event)
            canvas.transform_pos.assert_called_once_with(mock_event.pos())
            assert canvas.prev_point == canvas.transform_pos.return_value
            QApplication.setOverrideCursor.assert_called_once_with(QCursor(Qt.OpenHandCursor))
            canvas.select_shape_point.assert_called_once_with(canvas.transform_pos.return_value)

    def test_mousePressEvent_editing_right_click(self, qapp, button, module):
        with patch('Canvas.transform_pos'), patch('Canvas.select_shape_point'), patch(module, return_value=True):
            canvas = Canvas()
            mock_event = MagicMock()
            mock_event.button.return_value = button
            mock_event.pos.return_value = "some_event_position"
            canvas.mousePressEvent(mock_event)
            canvas.transform_pos.assert_called_once_with(mock_event.pos())
            assert canvas.prev_point == canvas.transform_pos.return_value
            canvas.select_shape_point.assert_called_once_with(canvas.transform_pos.return_value)

    @pytest.mark.invalid
    def test_mousePressEvent_invalid_mode_or_mouse_input(self, qapp, button, module):
        with patch('Canvas.transform_pos', return_value="transformed_point"), patch('Canvas.select_shape_point') as select_mock, patch('Canvas.handle_drawing') as drawing_mock, patch(module, return_value=False):
            canvas = Canvas()
            mock_event = MagicMock()
            mock_event.button.return_value = Qt.RightButton
            canvas.mousePressEvent(mock_event)
            drawing_mock.assert_not_called()
            select_mock.assert_not_called()
            canvas.mousePressEvent(QMouseEvent(QEvent.Type.MouseButtonPress, QPointF(500, 500), Qt.MiddleButton, Qt.NoButton, Qt.NoModifier))
            drawing_mock.assert_not_called()
            select_mock.assert_not_called()
