# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=highlight_clear_855149b2d6
ROOST_METHOD_SIG_HASH=highlight_clear_09f08eada8


Scenario 1: Testing the highlight_clear method when _highlight_index is not None
Details:
  TestName: test_highlight_clear_when_highlight_index_has_value
  Description: This test is designed to verify that the method highlight_clear correctly sets the value of _highlight_index to None when it initially has a value.
Execution:
  Arrange: An instance of the class will be created with a _highlight_index attribute set to some value other than None.
  Act: The highlight_clear method will be invoked on this instance.
  Assert: We will check that the instance's _highlight_index attribute is now None.
Validation:
  This test is crucial since the core functionality of the highlight_clear method is to set _highlight_index to None. Verifying this ensures the method is functioning as expected based on its specifications and business requirements.

Scenario 2: Testing the highlight_clear method when _highlight_index is None
Details:
  TestName: test_highlight_clear_when_highlight_index_is_none
  Description: This test is intended to verify the highlight_clear method's behavior when the value of _highlight_index is already None.
Execution:
  Arrange: An instance of the class will be created with a _highlight_index attribute set to None.
  Act: The highlight_clear method will be invoked on this instance.
  Assert: We will check that the instance's _highlight_index attribute remained None.
Validation:
  This test is important to verify the method's robustness. When _highlight_index is already None, executing highlight_clear should not cause any errors or change the _highlight_index value. If it does, the method may be erroneously modifying other object properties or behaving unpredictably in other ways.

Scenario 3: Testing the highlight_clear method when the class instance has other attributes
Details:
  TestName: test_highlight_clear_does_not_affect_other_attributes
  Description: This test aims to ensure that highlight_clear only modifies the _highlight_index attribute and does not change any other attribute in the class instance.
Execution:
  Arrange: An instance of the class will be created with _highlight_index and other attributes assigned specific values.
  Act: The highlight_clear method will be invoked on this instance.
  Assert: We will check that the other attributes remain the same before and after the highlight_clear invocation.
Validation:
  This test's significance lies in ensuring that the highlight_clear method does not have any unwanted side effects on other parts of the class instance. Integrity of the class instance and data encapsulation principles demand that highlight_clear should only modify _highlight_index.
"""

# ********RoostGPT********
# Importing required Libraries
import pytest
from shape import Shape

class Test_ShapeHighlightClear:

    @pytest.mark.regression
    def test_highlight_clear_when_highlight_index_has_value(self):
        # Arrange
        shape_instance = Shape()
        shape_instance._highlight_index = 5

        # Act
        shape_instance.highlight_clear()

        # Assert
        assert shape_instance._highlight_index is None

    
    @pytest.mark.regression
    @pytest.mark.negative
    def test_highlight_clear_when_highlight_index_is_none(self):
        # Arrange
        shape_instance = Shape()
        shape_instance._highlight_index = None

        # Act
        shape_instance.highlight_clear()
        
        # Assert
        assert shape_instance._highlight_index is None


    @pytest.mark.regression
    def test_highlight_clear_does_not_affect_other_attributes(self):
        # Arrange
        shape_instance = Shape('Shape1', 'red', True, True)
        shape_instance._highlight_index = 4
        initial_label = shape_instance.label
        initial_fill = shape_instance.fill
        initial_selected = shape_instance.selected
        initial_difficult = shape_instance.difficult
        initial_paint_label = shape_instance.paint_label

        # Act
        shape_instance.highlight_clear()

        # Assert
        assert shape_instance._highlight_index is None
        assert shape_instance.label == initial_label
        assert shape_instance.fill == initial_fill
        assert shape_instance.selected == initial_selected
        assert shape_instance.difficult == initial_difficult
        assert shape_instance.paint_label == initial_paint_label
