# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_bnd_box_8d12be0ba2
ROOST_METHOD_SIG_HASH=add_bnd_box_78b7840f75


```
Scenario 1: Test when bounding box details are correctly added to the box list
Details:
  TestName: test_add_bnd_box_successfully
  Description: This test verifies that the add_bnd_box function can successfully add bounding box details to the box list attribute.
Execution:
  Arrange: An instance of the class is required along with the boundary inputs for the function.
  Act: Call the add_bnd_box method with valid bounding box parameters (x_min, y_min, x_max, y_max, name, difficult).
  Assert: The box_list attribute of the instance should contain a dictionary matching the parameters passed to the add_bnd_box method.
Validation:
  This test is important because it validates the key business requirement of the function, which is adding bounding box details to the box list attribute.

Scenario 2: Test when bounding box details are the only elements in the box list
Details:
  TestName: test_add_bnd_box_as_only_element
  Description: This test verifies that add_bnd_box function correctly adds bounding box details when the box list is empty.
Execution:
  Arrange: An instance of the class with an empty box list is required, along with the boundary inputs for the function.
  Act: Call the add_bnd_box method with valid bounding box parameters (x_min, y_min, x_max, y_max, name, difficult).
  Assert: The box_list attribute of the instance should only contain one dictionary, which matches the parameters passed to the add_bnd_box method.
Validation:
  This test is key to confirming that the function correctly initializes the box list attribute when it is empty, thus maintaining data integrity.

Scenario 3: Test when multiple bounding box details are added to the box list
Details:
  TestName: test_add_bnd_box_multiple_calls
  Description: This test verifies that the add_bnd_box function can successfully add multiple bounding box details to the box list attribute.
Execution:
  Arrange: An instance of the class is required along with the boundary inputs for the function. The function is called multiple times with different bounding box parameters.
  Act: Call the add_bnd_box method with diverse sets of valid bounding box parameters.
  Assert: The box_list attribute of the class instance should contain multiple dictionaries each matching the parameters passed in each specific add_bnd_box method calls.
Validation:
  This test ensures the ability of the function to handle multiple bounding box details, meeting a vital project requirement of managing multiple bounding box entries as needed.
```
"""

# ********RoostGPT********
import pytest
import codecs
import os
from libs.constants import DEFAULT_ENCODING
from yolo_io import YOLOWriter

class Test_YoloWriterAddBndBox:
    """Class to test the add_bnd_box method of YOLOWriter"""

    @pytest.mark.valid
    def test_add_bnd_box_successfully(self):
        # Arrange
        yolo_writer = YOLOWriter('test_folder', 'test_file', (720, 1280), 'TestDB')
        x_min, y_min, x_max, y_max, name, difficult = 100, 200, 300, 400, 'person', False

        # Act
        yolo_writer.add_bnd_box(x_min, y_min, x_max, y_max, name, difficult)

        # Assert
        expected_box = {'xmin': x_min, 'ymin': y_min, 'xmax': x_max, 'ymax': y_max, 'name': name, 'difficult': difficult}
        assert yolo_writer.box_list[0] == expected_box

    @pytest.mark.valid
    def test_add_bnd_box_as_only_element(self):
        # Arrange
        yolo_writer = YOLOWriter('test_folder', 'test_file', (720, 1280), 'TestDB')
        x_min, y_min, x_max, y_max, name, difficult = 500, 600, 700, 800, 'cat', True

        # Act 
        yolo_writer.add_bnd_box(x_min, y_min, x_max, y_max, name, difficult)

        # Assert
        # Verify box_list has one entry
        assert len(yolo_writer.box_list) == 1
        expected_box = {'xmin': x_min, 'ymin': y_min, 'xmax': x_max, 'ymax': y_max, 'name': name, 'difficult': difficult}
        assert yolo_writer.box_list[0] == expected_box
            
    @pytest.mark.valid
    def test_add_bnd_box_multiple_calls(self):
        # Arrange
        yolo_writer = YOLOWriter('test_folder', 'test_file', (720, 1280), 'TestDB')
        box_params = [(10, 20, 30, 40, 'dog', False), (50, 60, 70, 80, 'car', True), (90, 100, 110, 120, 'tree', False)]

        # Act
        for params in box_params:
            yolo_writer.add_bnd_box(*params)

        # Assert
        # Verify box_list has multiple entries
        assert len(yolo_writer.box_list) == len(box_params)
        for i in range(len(box_params)):
            expected_box = {'xmin': box_params[i][0], 'ymin': box_params[i][1], 'xmax': box_params[i][2], 'ymax': box_params[i][3], 'name': box_params[i][4], 'difficult': box_params[i][5]}
            assert yolo_writer.box_list[i] == expected_box
