# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=contains_point_8b58d207a4
ROOST_METHOD_SIG_HASH=contains_point_8255b471ef


Scenario 1: Test when point exists within the boundary
Details:
  TestName: test_contains_point_within_boundary
  Description: This test validates whether the function correctly identifies a point as inside the boundary.
Execution:
  Arrange: Create a boundary object with specific points, and also create a separate point that is definitely within the boundary.
  Act: Invoke the function contains_point on the boundary object, passing the desired point.
  Assert: Validate that the function returns True, as the point is within the boundary.
Validation: 
  This test is significant because it verifies the main functionality of the contains_point function, that it correctly identifies points that are within the given boundary.

Scenario 2: Test when point exists outside the boundary
Details:
  TestName: test_contains_point_outside_boundary
  Description: This test validates whether the function correctly identifies a point as outside the boundary.
Execution:
  Arrange: Create a boundary object with specific points, and also create a separate point that is definitely outside the boundary.
  Act: Invoke the function contains_point on the boundary object, passing the desired point.
  Assert: Validate that the function returns False, as the point is outside the boundary.
Validation:
  This test is significant as it ensures that the function correctly identifies points that are outside the boundary.

Scenario 3: Test when point exists on the boundary
Details:
  TestName: test_contains_point_on_boundary
  Description: The test's goal is to verify whether the function correctly identifies a point that lies precisely on the boundary.
Execution:
  Arrange: Create a boundary using specific points and also create a separate point that lies exactly on the boundary.
  Act: Invoke the function contains_point on the boundary object, passing the desired point.
  Assert: Check that the function returns True, since the point lies on the boundary and should be considered as inside the boundary.
Validation:
  This test is vital because the contains_point function should return True if the point lies on the boundary, crucial for its correct functionality.

Scenario 4: Test with empty boundary
Details:
  TestName: test_contains_point_empty_boundary
  Description: This test ensures the function can handle an empty boundary and return False, regardless of the point's coordinates.
Execution:
  Arrange: Create an empty boundary (i.e., no points defined) and a point.
  Act: Invoke the function contains_point on the empty boundary, passing the desired point.
  Assert: Validate that the function returns False, as the point is not inside an empty boundary.
Validation: 
  This test is important because it verifies that the contains_point function can gracefully handle edge cases like an empty boundary.
  
Scenario 5: Test with a single point boundary
Details:
  TestName: test_contains_point_single_point_boundary
  Description: The test verifies the function's behavior when the boundary consists of a single point.
Execution:
  Arrange: Create a boundary with a single point and a separate point identical to the boundary point.
  Act: Invoke the function contains_point on the boundary, passing the identical point.
  Assert: Validate that the function returns True, as the point equals the single point boundary.
Validation:
  This test is essential because it checks an edge case of the contains_point function, ensuring its correctness when the boundary is a single point.
"""

# ********RoostGPT********
import pytest
from shape import Shape
from PyQt5.QtCore import QPointF
from PyQt5.QtGui import QPainterPath

class Test_ShapeContainsPoint:

    def test_contains_point_within_boundary(self):
        shape = Shape()
        shape.points = [QPointF(0, 0), QPointF(10, 0), QPointF(10, 10), QPointF(0, 10)]
        point = QPointF(5, 5)
        assert shape.contains_point(point) == True

    def test_contains_point_outside_boundary(self):
        shape = Shape()
        shape.points = [QPointF(0, 0), QPointF(10, 0), QPointF(10, 10), QPointF(0, 10)]
        point = QPointF(-5, -5)
        assert shape.contains_point(point) == False

    def test_contains_point_on_boundary(self):
        shape = Shape()
        shape.points = [QPointF(0, 0), QPointF(10, 0), QPointF(10, 10), QPointF(0, 10)]
        point = QPointF(10, 5)
        assert shape.contains_point(point) == True

    def test_contains_point_empty_boundary(self):
        shape = Shape()
        shape.points = []
        point = QPointF(5, 5)
        assert shape.contains_point(point) == False

    def test_contains_point_single_point_boundary(self):
        shape = Shape()
        shape.points = [QPointF(5, 5)]
        point = QPointF(5, 5)
        assert shape.contains_point(point) == True
