# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=bounded_shift_shape_fa96cb3e05
ROOST_METHOD_SIG_HASH=bounded_shift_shape_fed1892164


```
Scenario 1: Verify bounded shift when movable in both directions
Details:
  TestName: test_bounded_shift_in_both_directions
  Description: This test is intended to verify the bounded shift of shape when the shape is moveable in both directions i.e., left and up (-offset) or right and down (+offset). Move should successful in this scenario.
Execution:
  Arrange: Initialize a Canvas, its proper state. Set up a basic shape that can be moved in both directions i.e., the shape isn't adjacent to the boundary of the canvas.
  Act: Execute the `bounded_shift_shape` method against that shape.
  Assert: Check if the new position of the shape is updated after move operation.
Validation:
  The expected behaviour and business logic of `bounded_shift_shape` is to shift the shape within its bounded canvas. Hence, validation will help to ensure that the shape is indeed mobile and that the provided offset can successfully be applied.

Scenario 2: Verify bounded shift when movable in one direction only
Details:
  TestName: test_bounded_shift_in_one_direction
  Description: This test intends to verify the bounded shift of shape when shape is moveable in one direction only i.e., when the shape is near to the boundary and can only be moved right and down (+offset), but not left and up (-offset). Move should be successful in the allowable direction.
Execution:
  Arrange: Initialize a Canvas, its proper state. Set up a shape near to the border of canvas that is moveable only in one specified direction.
  Act: Execute the `bounded_shift_shape` method against that shape.
  Assert: Check if the new position of the shape is updated after the move operation.
Validation:
  The rational behind the test is to validate that, if a negative offset cannot be applied to a shape due to its proximity to a boundary, the function correctly reverses the offset to enable a movement in the available direction.

Scenario 3: Verify bounded shift without move
Details:
  TestName: test_bounded_shift_without_move
  Description: This test intends to verify the bounded shift of shape without any move i.e., when the shape is at a position where it can't be moved in any direction. In this case, shape's position would remain the same after the operation.
Execution:
  Arrange: Initialize a Canvas, its proper state. Set up a shape in such a position that it is immovable i.e., it is tightly bounded on all sides.
  Act: Execute the `bounded_shift_shape` method against that shape.
  Assert: Check if the position of the shape hasn’t changed after operation.
Validation:
  The purpose of this test is to check the function’s ability to handle scenarios where movement is impossible. This confirms that there are no unexpected outcomes when the shape cannot be moved.
```
"""

# ********RoostGPT********
import pytest
from libs.shape import Shape
from libs.utils import distance
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from canvas import Canvas


class Test_CanvasBoundedShiftShape:

    @pytest.mark.positive
    def test_bounded_shift_in_both_directions(self):
        canvas = Canvas()
        shape = Shape()
        shape.append_point(QPointF(20.0, 20.0))
        assert not canvas.bounded_move_shape(shape, QPointF(0.0, 0.0))
        canvas.bounded_shift_shape(shape)
        assert shape[0] == QPointF(22.0, 22.0)

    @pytest.mark.positive
    def test_bounded_shift_in_one_direction(self):
        canvas = Canvas()
        shape = Shape()
        shape.append_point(QPointF(0.0, 0.0))
        assert not canvas.bounded_move_shape(shape, QPointF(-2.0, -2.0))
        canvas.bounded_shift_shape(shape)
        assert shape[0] == QPointF(2.0, 2.0)

    @pytest.mark.negative
    def test_bounded_shift_without_move(self):
        canvas = Canvas()
        shape = Shape()
        shape.append_point(QPointF(-1.0, -1.0))
        assert not canvas.bounded_move_shape(shape, QPointF(-2.0, -2.0))
        assert not canvas.bounded_move_shape(shape, QPointF(2.0, 2.0))
        shape_pos_before = shape.points[0]
        canvas.bounded_shift_shape(shape)
        assert shape[0] == shape_pos_before, "Shape position should remain same"
