# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting3 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=save_pascal_voc_format_40d053fc1d
ROOST_METHOD_SIG_HASH=save_pascal_voc_format_c01ed17bd9


```
Scenario 1: Test for Successful Pascal VOC Content Saving
Details:
  TestName: test_save_pascal_voc_format_successful
  Description: This test is intended to verify that the function successfully saves content in Pascal VOC format when provided with valid parameters.
Execution:
  Arrange: Create a filename, shapes, image_path, and image_data. Initialize an instance of the class.
  Act: Invoke the save_pascal_voc_format function by passing the created parameters.
  Assert: Check that the function executes without throwing any exception and successfully saves content in Pascal VOC format.
Validation:
  This test is essential to ascertain the primary function of save_pascal_voc_format - to save content in the desired format. A successful operation confirms that the function can handle typical, valid data inputs.

Scenario 2: Test when image_data is not of QImage type
Details:
  TestName: test_save_pascal_voc_when_image_data_is_not_qimage
  Description: The test verifies whether the function handles scenarios where image_data provided is not an instance of QImage.
Execution:
  Arrange: Create a filename, shapes, and image_path. Pass image_data that is not an instance of QImage. Initialize an instance of the class.
  Act: Invoke the save_pascal_voc_format function with the created parameters.
  Assert: Check that the function successfully loads the image from the given image_path.
Validation:
  The test is critical in making sure that the function can handle cases where image_data provided is not an instance of QImage, and instead, load the image from the given image path.

Scenario 3: Test when the image is Grayscale
Details:
  TestName: test_save_pascal_voc_when_image_is_grayscale
  Description: This test verifies that the function correctly handles grayscale images.
Execution:
  Arrange: Create a filename, shapes, image_path, and grayscale image_data. Initialize an instance of the class.
  Act: Invoke the save_pascal_voc_format function with the created parameters.
  Assert: Confirm that the image_shape correctly sets channels to one, denoting grayscale images.
Validation:
  The test is crucial as it ensures that the function correctly interprets grayscale images, fundamental for processing image data in computer vision tasks by marking them with a single channel.

Scenario 4: Test Add Bounding Box
Details:
  TestName: test_save_pascal_voc_add_bounding_box
  Description: This test verifies if the function correctly adds the bounding box to the writer.
Execution:
  Arrange: Create a filename, shapes with 'points', 'label', 'difficult', image_path and image_data. Initialize an instance of the class.
  Act: Invoke the save_pascal_voc_format function with the parameters.
  Assert: Confirm that all the bounding boxes from shapes are correctly added to the writer.
Validation:
  The test is essential to verify the functionality of adding bounding boxes from given shapes, crucial for creating the desired format containing the necessary annotations.```

"""

# ********RoostGPT********
import pytest
from PyQt5.QtGui import QImage
import os.path
from labelFile import LabelFile

class Test_LabelFileSavePascalVocFormat:
    def test_save_pascal_voc_format_successful(self):
        filename = os.path.join(os.path.dirname(__file__), "test_data", "test_file.xml")
        shapes = [{'points': [(10, 10), (20, 20)], 'label': 'test', 'difficult': '1'}]
        image_path = os.path.join(os.path.dirname(__file__), "test_data", "test_image.jpg")
        image_data = QImage(image_path)
        label_instance = LabelFile()
        try:
            label_instance.save_pascal_voc_format(filename, shapes, image_path, image_data)
        except:
            pytest.fail("Unexpected Error ..!")

    def test_save_pascal_voc_when_image_data_is_not_qimage(self):
        filename = os.path.join(os.path.dirname(__file__), "test_data", "test_file_noQImage.xml")
        shapes = [{'points': [(10, 10), (20, 20)], 'label': 'not_qimage', 'difficult': '1'}]
        image_path = os.path.join(os.path.dirname(__file__), "test_data", "test_image_noQImage.jpg")
        image_data = "This is not a QImage"
        label_instance = LabelFile()
        try:
            label_instance.save_pascal_voc_format(filename, shapes, image_path, image_data)
        except:
            pytest.fail("Unexpected Error ..!")

    def test_save_pascal_voc_when_image_is_grayscale(self):
        filename = os.path.join(os.path.dirname(__file__), "test_data", "test_file_gray_scale.xml")
        shapes = [{'points': [(10, 10), (20, 20)], 'label': 'gray_scale', 'difficult': '1'}]
        image_path = os.path.join(os.path.dirname(__file__), "test_data", "test_image_gray_scale.jpg")
        image_data = QImage(image_path).convertToFormat(QImage.Format_Grayscale8)
        label_instance = LabelFile()
        try:
            label_instance.save_pascal_voc_format(filename, shapes, image_path, image_data=image_data)
            assert label_instance.image_shape == [image_data.height(), image_data.width(), 1]
        except:
            pytest.fail("Unexpected Error ..!")

    def test_save_pascal_voc_add_bounding_box(self):
        filename = os.path.join(os.path.dirname(__file__), "test_data", "test_file_bnd_box.xml")
        shapes = [{'points': [(10, 10), (20, 20)], 'label': 'bnd_box', 'difficult': '1'}]
        image_path = os.path.join(os.path.dirname(__file__), "test_data", "test_image_bnd_box.jpg")
        image_data = QImage(image_path)
        label_instance = LabelFile()
        try:
            label_instance.save_pascal_voc_format(filename, shapes, image_path, image_data)
            for shape in shapes:
                assert label_instance.shapes.contains(shape)
        except:
            pytest.fail("Unexpected Error ..!")

